### DISCUSSION TITLE
isort: adding namespace as known-first-party

### DISCUSSION THREAD

**Discussion by higorc-mck** [astral-sh/ruff#10053] [Q&A]
I have a monorepo that holds many different namespace packages, almost all of them belonging to the same namespace. I can't get `ruff` to recognize the namespace as first party, not through name matching nor path matching, as the documentation is a bit ambiguous:

>A list of modules to consider first-party, regardless of whether they can be identified as such via introspection of the local filesystem.
>Supports glob patterns. For more information on the glob syntax, refer to the [globset documentation](https://docs.rs/globset/latest/globset/#syntax).

In my `pyproject.toml`, I have tried the following:

- Matching the namespace name
  ```toml
  [tool.ruff.lint.isort]
  known-first-party = ["my_namespace"]
  ```

- Matching all paths for these packages
  ```toml
  [tool.ruff.lint.isort]
  known-first-party = ["relative_path/**/to/**/namespace/**"]
  ```

Neither option worked. Am I doing something wrong?

**Comment by yoann9344** [comment]
Maybe, for now, you should create a new group ? Then if it doesn't work neither it could give more clues on the issue.
```toml
[tool.ruff.lint.isort]
section-order = ["future", "standard-library", "third-party", "my_packages", "first-party", "local-folder"]

[tool.ruff.lint.isort.sections]
"my_packages" = ["namespace1", "ns2", "ns3"]
```
Then which command did you try, to see that it is not recognized ? Is this one work ?
```bash
ruff --version
ruff check --select I --diff
# Then to apply changes to the files
ruff check --select I --fix
```
