### DISCUSSION TITLE
`--fix-only`, but for just a specific rule

### DISCUSSION THREAD

**Discussion by jamesbraza** [astral-sh/ruff#10106] [Q&A]
I like [ANN201](https://docs.astral.sh/ruff/rules/missing-return-type-undocumented-public-function/)'s autofix because it adds `-> None` to functions where possible.  However, in general, I don't like enforcing a requirement to specify return types.

From my `pyproject.toml` config file:

```toml
[tool.ruff]
unsafe-fixes = true

[tool.ruff.lint]
ignore = [
    "ANN",
]
select = ["ALL"]

[tool.ruff.lint.flake8-annotations]
mypy-init-return = true
```

This enables the autofixes for ANN201, but also makes it a requirement to always pass.

In general, I am looking for something like `--fix-only`, but instead of being global, it is scoped to specific rules. Is there some way to have `--fix-only` for specific rule codes?

**Comment by DavidCain** [comment]
A way to work around this is to define a custom `ruff.toml` configuration that you use _only_ for auto-applying `ANN201`:

```toml
extend = "pyproject.toml"

# This special configuration is meant to *only* autofix typing issues.
fix-only = true

[lint]
extend-safe-fixes = ["ANN201"]
select = ["ANN201"]
```

Then, invoking `ruff check --config ruff_ann.toml` will autofix ANN201 violations!
