### DISCUSSION TITLE
Does ruff's sort implementation support fuzzy matching for custom sections?

### DISCUSSION THREAD

**Discussion by ahgraber** [astral-sh/ruff#11308] [General]
I'd like to add a custom `llm` section to my `[tool.ruff.isort.sections]` portion of my pyproject.toml.  
The recent refactoring of `langchain` and `llama-index` mean that they now require libraries of packages (`langchain-core`, `langchain-openai`, `langchain-google-genai`, etc).

Is it possible to do something like and have ruff do a fuzzy match on import name?  Example with globs:

```toml
...
[tool.ruff.isort.sections]
"llm" = ["langchain*", "llama-index*"]
```
