### DISCUSSION TITLE
Different results between CLI and Pre-Commit

### DISCUSSION THREAD

**Discussion by GoncaloGuedes** [astral-sh/ruff#11924] [Q&A]
I've set up a pre-commit hook using Ruff to handle linting in my project. I've configured the hook as per the [documentation][1]:

```yaml
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.9
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
```

To test this setup, I've created a script a.py with the following content:

```python

"""Module contains functions related to greetings."""

def get_greeting(name: str) -> str:
    """Return a greeting message.

    Args
        name (str): Name of the person to greet.

    Returns
        str: A greeting message.

    """
    return f"Hello, {name}!"

def hello() -> str:
    return "hello"
```

Running ruff check from the command line gives me 3 errors:

    a.py:8:5: D416 [*] Section name should end with a colon ("Args")
    a.py:12:5: D416 [*] Section name should end with a colon ("Returns")
    a.py:20:5: D103 Missing docstring in public function
    Found 3 errors.
    [*] 2 fixable with the `--fix` option.

However, when I run pre-commit, it passes without any errors. Am I missing something in my configuration?

  [1]: https://docs.astral.sh/ruff/integrations/#pre-commit
