### DISCUSSION TITLE
Config to disable automatic line wrapping

### DISCUSSION THREAD

**Discussion by tva-subteno-it** [astral-sh/ruff#12186] [Q&A]
Hi there, 
I was wondering if there was any config to disable the automatic line wrapping of ruff? In my code, all the lines already fit within the line-length configured, and yet my code gets formatted with line break after every parenthesis, curly braces, even within list indexes when ruff is used (btw, I use it with pre-commit).

For instance, this code has the right size:

```py
order["data"]["amount_total"] = order["data"]["statement_ids"][0][2].get("amount")
```

but was formatted like this:

```py
order["data"]["amount_total"] = order["data"]["statement_ids"][0][
    2
].get("amount")
```

**Comment by MichaReiser** [comment]
Hi

I tried to reproduce your example but I wasn't able to, at least with the default line-length of 88 unicode code points ([playground](https://play.ruff.rs/30cc0d40-1bc0-4ff8-a5dc-22d9908921a6?secondary=Format)).

Can you share your `line-length` configuration with me?

**Reply by tva-subteno-it** [reply]
I found the solution : I needed to add the ruff config file to the ruff format as well as the ruff linter. 

I had this:

```yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args:
        - --fix
        - --config=/home/tva/Projects/Tools/pre-commit-config/.ruff.toml
      - id: ruff-format
```

But I needed this:

```yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args:
        - --fix
        - --config=/home/tva/Projects/Tools/pre-commit-config/.ruff.toml
      - id: ruff-format
        args:
          - --config=/home/tva/Projects/Tools/pre-commit-config/.ruff.toml
```
