### DISCUSSION TITLE
Including rules in `extend-select` does not work but including them in `select` works.

### DISCUSSION THREAD

**Discussion by seanswyi** [astral-sh/ruff#12345] [Q&A] [answered]
I recently came across a problem where my Ruff configuration was not using isort. After doing some investigation, I realized that I needed to change the `.ruff.toml` file as follows:

```TOML
# Before
[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = ["E4", "E7", "E9", "F"]
ignore = []
extend-select = ["I"]

# After
[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = ["E4", "E7", "E9", "F", "I"]
```

I came across this other question here (https://github.com/astral-sh/ruff/discussions/10753) which led me to the documentation (https://docs.astral.sh/ruff/linter/#rule-selection). What's confusing me is shouldn't both configurations work identically?

Or is `"I"` ignored because it's not set inside of `select`?

**Comment by dhruvmanila** [comment]
That should work (https://play.ruff.rs/f19993ec-ee4e-42c4-b92a-cd7c976bf1de), I tested it locally as well using `.ruff.toml`. Can you share how you're running Ruff itself? Is it on the command-line, editor, or pre-commit? If it's the editor, is it using [`ruff-lsp`](https://github.com/astral-sh/ruff-lsp) or the new `ruff server`?

**Comment by seanswyi** [comment]
I'm currently using Ruff as a pre-commit hook. Pre-commit is being installed using Poetry.

I'm also a little confused as to what the problem was, or if the solution actually is changing the options or was something else. If it's certain that both of the code samples above should work identically, I believe it would be safe to close this question.

**Reply by dhruvmanila** [reply]
Yeah, the code samples mentioned above should work but I'm happy to resolve your issue. Can you share the pre-commit config? I can check it out and confirm if the setup is correct.

**Reply by seanswyi** [reply]
Sure.

This is the pre-commit config:

```YAML
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.5.0
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
```

This is the Ruff config that I changed:

```TOML
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 120
indent-width = 4

# Assume Python 3.8
target-version = "py311"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = ["E4", "E7", "E9", "F", "I"] 
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[lint.isort]
# Use a single line after each import block.
lines-after-imports = 2
```
