### DISCUSSION TITLE
How to format short content into single line?

### DISCUSSION THREAD

**Discussion by failable** [astral-sh/ruff#12983] [Q&A] [answered]
In black, this 

```python
print(
    a,
    b
)
```

will be formatted into 

```python
print(a, b)
```

if there is NO trailing comma after `b`.

I understand if there's a trailing comma or the content it too long, it should be kept like

```python
print(
    a,
    b,
)
```

This happens quite often to me when I modify / remove the function arguments and I am pretty sure it's short enough to fit in a single line. Currently I have to join each lines manually to make it a single line.

How can I achieve this (format short content in single line when there is no trailing comma) in Ruff? Thanks.

**Comment by MichaReiser** [comment]
Hi @failable 

Running `ruff format` (not `check`) should apply the same styling as Black. See [this playground](https://play.ruff.rs/49700529-ffa1-49aa-8305-3c306531f919?secondary=Format) where the right panel shows the formatted code.

**Reply by failable** [reply]
@MichaReiser Thanks for the confirmation. I'm using the Zed config from [here](https://docs.astral.sh/ruff/editors/setup/#zed)

```json
{
  "languages": {
    "Python": {
      "format_on_save": "on",
      "formatter": [
        {
          "code_actions": {
            "source.organizeImports.ruff": true,
            "source.fixAll.ruff": true
          }
        },
        {
          "language_server": {
            "name": "ruff"
          }
        }
      ]
    }
  }
}
```

It seems that the issue is the fix action run before  (thus trailing comma is inserted) the later formatter. 

If I switch the order of them, will the code action result guarantee to be formatted? Or should I use a `format` - `fix` - `format` combination to get desired result of my original post?

**Reply by MichaReiser** [reply]
Hmm, I wonder if you're running into a situation where you use a setting that's incompatible with the formatter. What's your ruff configuration in `pyproject.toml` or `ruff.toml` (if any)?

**Reply by failable** [reply]
Below is my `ruff.toml` and I don't have ruff setup in my `pyproject.toml`.

```toml
target-version = "py310"
src = ["src"]

[lint]
select = ["ALL"]
ignore = [
    # Missing dostring
    # https://beta.ruff.rs/docs/rules/#pydocstyle-d
    "D10",
    "D203", # conflicts with D211
    "D213", # conflicts with D212
    # TODO
    # https://beta.ruff.rs/docs/rules/#flake8-todos-td
    "TD",
    # FIXME
    # https://beta.ruff.rs/docs/rules/#flake8-fixme-fix
    "FIX",
    # `random` library
    # https://beta.ruff.rs/docs/rules/suspicious-non-cryptographic-random-usage/
    "S311",
    # Type annotation
    # https://beta.ruff.rs/docs/rules/#flake8-annotations-ann
    "ANN",
    # https://beta.ruff.rs/docs/rules/#flake8-use-pathlib-pth
    "PTH",
    # https://beta.ruff.rs/docs/rules/#flake8-print-t20
    "T20",
    # UTF-8 encoding declaration is unnecessary
    # https://beta.ruff.rs/docs/rules/#pyupgrade-up UTF-8 encoding declaration is unnecessary
    "UP009",
    # Found commented-out code
    # https://beta.ruff.rs/docs/rules/commented-out-code/
    "ERA001",
    # Trailing comma prohibited
    # https://docs.astral.sh/ruff/rules/prohibited-trailing-comma/
    "COM819",
    # df is a bad variable name. Be kinder to your future self.
    # https://beta.ruff.rs/docs/rules/pandas-df-variable-name/
    "PD901",
    # Missing copyright notice
    # https://docs.astral.sh/ruff/rules/missing-copyright-notice/
    "CPY001",
]

[lint.pydocstyle]
convention = "google"

[lint.per-file-ignores]
"__init__.py" = ["E402"]
"tests/**/*.py" = [
    "S101",    # asserts allowed in tests...
    "ARG002",  # Unused function args -> fixtures nevertheless are functionally relevant...
    "PLR6301",
    # "FBT",  # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    # # The below are debateable
    "PLR0904",
    "PLR2004", # Magic value used in comparison, ...
    # "S311",    # Standard pseudo-random generators are not suitable for cryptographic purposes
]
```
