### DISCUSSION TITLE
Ruff auto add parentheses to a long line of code

### DISCUSSION THREAD

**Discussion by bavo96** [astral-sh/ruff#13582] [Q&A] [answered]
I have a very long line of code like this:
```python
this_is_a_very_long_variable = 1
this_is_another_ver_long_variable = 2
this_is_the_last_long_variable = 3

message = this_is_a_very_long_variable + this_is_another_ver_long_variable + this_is_the_last_long_variable
```

When I run formatting using ruff, the line is separated into multiple lines, but the point is it also generates parentheses at the beginning and the end of the value like this:
```python
this_is_a_very_long_variable = 1
this_is_another_ver_long_variable = 2
this_is_the_last_long_variable = 3

message = (
    this_is_a_very_long_variable
    + this_is_another_ver_long_variable
    + this_is_the_last_long_variable
)
```
This causes the `message` variable to become a tuple, and if i wanna get the value of it, i have to write `message[0]`. This is dangerous if we use this inside a code project :( Is there a way to remove the parentheses from auto formatting? Any help would be appreciated <3

My current Ruff's config:
```toml
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.8
target-version = "py38"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
```
