### DISCUSSION TITLE
Which `pre-commit-hooks` are Available in `ruff`?

### DISCUSSION THREAD

**Discussion by adam-grant-hendry** [astral-sh/ruff#14647] [Q&A]
Of the following `pre-commit-hooks`, which are available in `ruff`?:

```yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-docstring-first
        name: (pre-commit-hooks) Check docstrings defined before code
      - id: name-tests-test
        name: (pre-commit-hooks) Check tests named correctly ('test_*.py')
        args: [
            "--django", # `test_*.py` style
          ]
      - id: check-merge-conflict
        name: (pre-commit-hooks) Check no files contain merge conflict strings
      - id: check-toml
        name: (pre-commit-hooks) Check TOML files parseable
      - id: check-yaml
        name: (pre-commit-hooks) Check YAML files parseable
```
