### DISCUSSION TITLE
Automatically Wrap Long Line Comments

### DISCUSSION THREAD

**Discussion by laguill** [astral-sh/ruff#14812] [Q&A] [answered]
Hello,
Is it possible to raise a warning when comments are too long and I should split it a something smaller ?

**Comment by MichaReiser** [comment]
Is [W505](https://docs.astral.sh/ruff/rules/doc-line-too-long/) what you're looking for? You can enable it with `extend-select = ["W505"]`

**Comment by laguill** [comment]
I modified my pyproject.toml with W505 and max-doc-lenght but without success
```toml
[tool.ruff]
line-length = 120
extend-include = [
  "*.ipynb",
  "*.qmd"]

[tool.ruff.format]
preview = true
quote-style = "double"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN",     # Mypy is better at this
  "COM",     # Formatter takes care of our commas
  "E501",    # leave line-length enforcement to formatter
  "T201",    # I am using print
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",    # D100-104 missing docstring
  "D107",    # undocumented-public-init
  "INP001",  # missing __init__ in external library
]
# Add the `line-too-long` rule to the enforced rule set.
extend-select = ["W505"]

[tool.ruff.lint.isort]
lines-between-types = 1
lines-after-imports = 2

[tool.ruff.lint.pydocstyle]
convention = "google"
max-doc-length = 120
```

Also when I run `ruff check myfile.py`
I get this error
```bash
  Cause: TOML parse error at line 47, column 1
   |
47 | [tool.ruff.lint]
   | ^^^^^^^^^^^^^^^^
unknown field `max-line-length`, expected one of `convention`, `ignore-decorators`, `property-decorators`
```

**Reply by MichaReiser** [reply]
It seems you have a configuration somewhere that specifies `max-line-length` under `[tool.ruff.lint]` which is incorrect but it isn't the configuration above. Can you run ruff with `ruff check -v` to see which configuration ruff picks up?

**Reply by laguill** [reply]
My bad I pasted the wrong shell output
This is the correct error I get

```bash
  Cause: TOML parse error at line 46, column 1
   |
46 | [tool.ruff.lint]
   | ^^^^^^^^^^^^^^^^
unknown field `max-doc-length`, expected one of `convention`, `ignore-decorators`, `property-decorators`
```

**Reply by MichaReiser** [reply]
You have to move the `max-doc-length` into the py**codestyle** (not docstyle) section

```toml
[tool.ruff.lint.pycodestyle]
max-doc-length = 88
```
