### DISCUSSION TITLE
COM812 fails even with one line of code and it's autofix doesn't respect line-length

### DISCUSSION THREAD

**Discussion by koevgeny10** [astral-sh/ruff#16369] [Ideas]
The documentation has an example with a 2-line dictionary. But it fails even with one line of code.

Versions:
* Python: 3.13
* ruff: 0.9.7

pyproject.toml
```toml
[tool.ruff]
target-version = "py313"
line-length = 79
output-format = "concise"

[tool.ruff.lint]
select = ["COM812",  "E501"]
```

```python
def a(
    b, cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
): pass
```
Ruff reports:
```
a.py:2:80: COM812 [*] Trailing comma missing
Found 1 error.
[*] 1 fixable with the `--fix` option.
```

I propose that COM812 doesn't fail in such cases.

And it's autofix doesn't respect `line-length` and adds comma at character 80. Then E501 fails.
