### DISCUSSION TITLE
How to configure `Ruff` to apply all rules?

### DISCUSSION THREAD

**Discussion by Tomperez98** [astral-sh/ruff#3419] [Q&A] [answered]
I want to set ruff to apply all rules something like.

```toml
[tool.ruff]

select = [
  "*"
]
```

**Comment by edgarrmondragon** [comment, marked as answer]
I couldn't find it documented anywhere, but the `ALL` code will select all available rules:

```toml
[tool.ruff]
select = [
  "ALL",
]
```
