### DISCUSSION TITLE
Why is `line-length` not propagating from top-most `pyproject.toml`?

### DISCUSSION THREAD

**Discussion by jamesbraza** [astral-sh/ruff#4155] [Q&A] [answered]
I have a `pyproject.toml` in the repo root:

```toml
# pyproject.toml

[tool.ruff]

line-length = 97
```

I have a `test` subdirectory that has its own `pyproject.toml`

```toml
# test/pyproject.toml

[tool.ruff]

ignore = [
    "S101",  # assert gets used in tests
]
```

For some reason, the updated `line-length` isn't propagating into the `test` directory.  The `test` directory is still using `88` as its length.

Might this be a bug, or am I missing something?
