### DISCUSSION TITLE
Do not flag docstrings and comments lines with E501(linz-too-long) warnings

### DISCUSSION THREAD

**Discussion by vianmixtkz** [astral-sh/ruff#4982] [Q&A]
Ruff flags my docstrings and comments line that go over the specified limits with E501 and I don't like that.
How can I configure Ruff so that it ignores docstrings and comments when counting the number of characthers ?

I don't want it to flag my docstrings with lines that go over 80 characthers or lines that are pure comments line (i.e that starts with #) or even mixed lines (i.e lines that start with code and finishes with a comment)

**Comment by dhruvmanila** [comment]
Line length for docstrings and comments can be updated using [`max-doc-length`](https://beta.ruff.rs/docs/settings/#pycodestyle-max-doc-length) option which is independent to the [`line-length`](https://beta.ruff.rs/docs/settings/#line-length) option.

```toml
[tool.ruff]
select = ["E", "W"]
line-length = 88

[tool.ruff.pycodestyle]
max-doc-length = 79
```

As for the mixed lines which contains trailing comments, it seems like only `E501` is triggered when it goes beyond the `line-length` limit. The `W505` won't be triggered even if it goes beyond the `max-doc-length` range. Is this the expected behavior? @charliermarsh

**Reply by vianmixtkz** [reply]
Does not seem to work as expected the error code that I receive on comments and docstrings is E501 not W505

![image](https://github.com/astral-sh/ruff/assets/122097976/3f1206c2-b168-423f-a63f-730dde5f8246)

**Reply by charliermarsh** [reply]
I think your Ruff may be misconfigured. I tested locally, and the provided settings behave correctly for me. Are you able to share your configuration?

**Reply by charliermarsh** [reply]
(And yes, it's intentional that "doclines" does not include end-of-line comments, which is consistent with Flake8.)

**Reply by vianmixtkz** [reply]
I used the following configuration

```toml
[tool.ruff]
select = ["E", "F", "D100", "D101", "D102", "D103", "D104", "D105", "D106"]
line-length = 120

[tool.ruff.pycodestyle]
max-doc-length = 200
```
