### DISCUSSION TITLE
How to include parent directories in globs when running from subdirectory

### DISCUSSION THREAD

**Discussion by tgross35** [astral-sh/ruff#5284] [Q&A]
Is it possible to exclude files in a parent directory when `ruff` is invoked from within a subdirectory? Such as with this sample file layout:

```
/checkout/
    .gitignore
    obj/           <-- ruff run from here
    src/
        llvm-project/
            ...    <-- want to exclude everything in here
        ruff.toml
```

Config:

```toml
select = ["B", "E", "EXE", "F"]

# Ignore all submodules
extend-exclude = [
    # works only when running from /checkout but not from obj/
    "src/llvm-project/",
    # Doesn't do anything
    "**/src/llvm-project/",
    # ...
]
```

Ruff invocation:

```sh
python3 -m ruff --diff --config /checkout/src/ruff.toml /checkout
```

Setting `../src/llvm-project/` does the trick, but is there a glob way without hard coding the `../`? Such that running `ruff /checkout` from anywhere on the file system would correctly exclude that directory.
