### DISCUSSION TITLE
Ruff does not respect configurations to exclude certain directories

### DISCUSSION THREAD

**Discussion by jarmos-san** [astral-sh/ruff#5857] [Q&A] [answered]
So, our current project follows a directory structure like this:

```
.
├── backend/
│   ├── ...
│   ├── some-file.py
│   └── ...
├── frontend/
│   ├── ...
│   ├── some-file.tsx
│   └── ...
├── another-service/
│   ├── ...
│   ├── some-file.py
│   └── ...
└── migrations/
    ├── env.py
    ├── README
    ├── script.py.mako
    └── ...
```
We don't want `ruff` to lint/format the generated files under the `migrations` directory. So far we tried configuring the `pyproject.toml` with the following entries:

```toml
[tool.ruff]
extend-select = ["D", "I", "RUF"]
ignore = ["D211", "D212"]
extend-exclude = ["migrations"]
```
But `ruff` still performs linting for some of the Python files located under the `migrations` directory. What's going on over here? Are our configurations wrong or is there something else we're probably missing out on?
