### DISCUSSION TITLE
Convert to 3.10 Typing Syntax?

### DISCUSSION THREAD

**Discussion by kmcentush** [astral-sh/ruff#6020] [General]
I know that ruff has the ability to move type-specific imports into a type checking block at the top of the file (aside: how to do I enable that?), but I was wondering if it also had the ability to force-convert all types into the 3.10 syntax. i.e. `List[str]` -> `list[str]`, etc.

Thanks!

**Comment by charliermarsh** [comment]
Yup! We have rules for that: [`non-pep585-annotation`](https://beta.ruff.rs/docs/rules/non-pep585-annotation/) and  [`non-pep604-annotation`](https://beta.ruff.rs/docs/rules/non-pep604-annotation/).

You'd turn them on like:

```toml
[tool.ruff]
extend-select = ["UP"]
target-version = "py310"
```

That enables all the "upgrade"-related rules, but you can be more targeted if you want:

```toml
[tool.ruff]
extend-select = [
  "UP006",  #  non-pep585-annotation
  "UP007",  #  non-pep604-annotation
]
target-version = "py310"
```
