### DISCUSSION TITLE
Issue with ruff running through pre-commit on Bitbucket Pipelines

### DISCUSSION THREAD

**Discussion by zeshuaro** [astral-sh/ruff#6191] [Q&A]
Maybe this is just a config issue across multiple tools and/or the CI platform, but I'm having trouble getting ruff running properly through pre-commit on Bitbucket Pipelines.

You can see this sample repository that I've setup on Bitbucket: https://bitbucket.org/zeshuaro/r0/src/master/

I have a very basic config for ruff:

```toml
[tool.ruff]
select = ["ALL"]

[tool.ruff.pydocstyle]
convention = "google"
```

And using a local hook for pre-commit:

```yml
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        types: [python]
        args:
          - --force-exclude
          - --verbose
```

I'm also using the sample Python code from the docs, where ruff should identify a couple of issues:

```python
from typing import List

import os


def sum_even_numbers(numbers: List[int]) -> int:
    """Given a list of integers, return the sum of all even numbers in the list."""
    return sum(num for num in numbers if num % 2 == 0)
```

When running pre-commit locally via `pre-commit run --all-files`, everything works as expected:

```
ruff.....................................................................Failed
- hook id: ruff
- exit code: 1

[2023-07-31][20:34:12][ruff_cli::commands::run][DEBUG] Identified files to lint in: 443.208µs
[2023-07-31][20:34:12][ruff_cli::commands::run][DEBUG] Checked 1 files in: 14.708µs
main.py:1:1: UP035 `typing.List` is deprecated, use `list` instead
main.py:1:1: D100 Missing docstring in public module
main.py:1:1: I001 [*] Import block is un-sorted or un-formatted
main.py:3:8: F401 [*] `os` imported but unused
main.py:6:31: UP006 [*] Use `list` instead of `List` for type annotation
Found 5 errors.
[*] 3 potentially fixable with the --fix option.
```

However, when running pre-commit on Bitbucket Pipelines, ruff doesn't identify any issues as shown here: https://bitbucket.org/zeshuaro/r0/pipelines/results/6

```
ruff.....................................................................Passed
- hook id: ruff
- duration: 0.01s
[2023-07-31][10:30:36][ruff::resolver][DEBUG] Ignored path via `exclude`: "/opt/atlassian/pipelines/agent/build"
[2023-07-31][10:30:36][ruff_cli::commands::run][DEBUG] Identified files to lint in: 720.875µs
warning: No Python files found under the given path(s)
```

Based on the debugging logs, it seems like the Python file didn't get pick up because it was under the directory `/opt/atlassian/pipelines/agent/build`, which makes sense because ruff ignores the `build` directory by default, I believe. And I confirmed with a `pwd` that the above directory is the working directory on Bitbucket Pipelines.

I guess the easy workaround is to override the `exclude` config and not include the `build` directory. But I don't want to do this because packaging produces the `build` directory and I don't want ruff to run against it (specifically in the local environment I guess).

So my question is what's the recommendation to configure ruff or the other tools in this case?

**Comment by charliermarsh** [comment]
Removing `--force-exclude` from the configuration may fix it, trying to think on whether there'd be a better solution here. Your diagnosis sounds right to me.

**Reply by zeshuaro** [reply]
Thanks for the suggestion. That does get around the sample repo I have to get ruff to report the errors. But would cause issue if I do have a list of files/directories that I want to exclude for ruff. E.g.

```toml
[tool.ruff]
select = ["ALL"]
extend-exclude = ["docs"]
```

And let's say I copy `main.py` into `docs` folder which I do want ruff to exclude, without `--force-exclude`, it will still be picked up. See this branch: https://bitbucket.org/zeshuaro/r0/src/no-force-exclude/ and the build results: https://bitbucket.org/zeshuaro/r0/pipelines/results/7

**Comment by roshanjrajan-zip** [comment]
Hi, I'm getting a similar problem on my private repo. I am on ruff 0.0.282. I am gettting this particularly when converting our repo to use ruff isort versus isort. On a linux VM using x86 ruff passes, on a docker/macbook arm i it fails on a subset of files, in CI on ubuntu-latest which is x86 it fails on a large number of files that are different that the docker/macbook subset. Any ideas?
```toml
select = [
  "F401", # unused-import
  "I", # isort
]

exclude = [
  ".git",
  "__pycache__",
  "gen-py",
]

line-length = 88
target-version = "py311"
```
```yaml
ruff:
  runs-on: ubuntu-latest

  steps:
    - name: Check out Git repo
      uses: actions/checkout@v3
    - name: Run ruff
      uses: chartboost/ruff-action@2bc585f1253832f5a5220d7fbf86976822116147
      with:
        src: "./src"
        version: 0.0.282
```
