### DISCUSSION TITLE
[PT011] I want to disallow calling `pytest.raises` without `match` regardless of the error type.

### DISCUSSION THREAD

**Discussion by harupy** [astral-sh/ruff#6382] [Q&A]
I want to disallow calling `pytest.raises` without `match` **regardless of the error type**. Is there a way to achieve that? We could use [raises-require-match-for](https://beta.ruff.rs/docs/settings/#flake8-pytest-style-raises-require-match-for) and specify all error types in a codebase there, but that's exhausting.

```toml
[tool.ruff.flake8-pytest-style]
raises-require-match-for = ["ALL", "ERROR", "TYPES", "IN", "THIS", "REPO", "..."]
```
