### DISCUSSION TITLE
Why I see so much strange ruff segfaults?

### DISCUSSION THREAD

**Discussion by qarmin** [astral-sh/ruff#7612] [Q&A]
When I run checking with ruff . --fix a lot of files, then I nothing special happens.

When I do this in parallel, then results are still "good"(sometimes ruff exits with status 1, because it found bugs in code) and nothing else is printed into output - no panic/crashes etc, but in system journal I see such messages
```
wrz 22 22:15:25 H87M-D3H kernel: ruff[454275]: segfault at 7fe96be038d8 ip 000055b80919d69a sp 00007fe9719fd6a0 error 6 likely on CPU 4 (core 0, socket 0)
wrz 22 22:15:25 H87M-D3H kernel: Code: 00 00 66 0f ef c0 31 c9 48 8d b8 a8 28 00 00 c7 40 04 00 00 00 00 48 c7 40 10 00 00 00 00 ba 0f 00 00 00 48 8d 35 cd 0b 2e 00 <0f> 11 80 98 28 00 00 e8 da 5f 05 00 84 c0 0f 85 ea 00 00 00 e8 bd
wrz 22 22:15:28 H87M-D3H kernel: ruff[460385]: segfault at 7fa648dfcfe8 ip 00007fa64a28eeac sp 00007fa648dfcfe0 error 6 likely on CPU 5 (core 1, socket 0)
wrz 22 22:15:28 H87M-D3H kernel: Code: 35 77 72 12 00 48 8d 3d 81 72 12 00 e8 ed 4a fa ff 45 31 ed e9 5c fe ff ff 0f 1f 44 00 00 f3 0f 1e fa 41 54 55 53 48 83 c4 80 <48> 89 7c 24 08 64 48 8b 04 25 28 00 00 00 48 89 44 24 78 31 c0 80
```

I tried to use both valgrind and asan with ruff, but I did not find anything

**Comment by MichaReiser** [comment]
I'm not sure what's going on. Could you share some more details about your OS, OS, CPU architecture etc...

**Reply by dhruvmanila** [reply]
Additionally, can you also explain how you ran in parallel? Did you use [`parallel`](https://www.mankier.com/1/parallel) command?

**Reply by qarmin** [reply]
```
System:
  Host: rafal-H87M-D3H Kernel: 6.2.0-33-generic arch: x86_64 bits: 64
    compiler: N/A Desktop: GNOME v: 44.3 Distro: Ubuntu 23.04 (Lunar Lobster)
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    vendor: Sapphire driver: amdgpu v: kernel arch: GCN-4 bus-ID: 01:00.0
    temp: 49.0 C
  Display: x11 server: X.Org v: 1.21.1.7 with: Xwayland v: 22.1.8 driver: X:
    loaded: amdgpu unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi
    gpu: amdgpu resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6 Mesa 23.0.4 (git-896db04e02) renderer: AMD Radeon RX
    570 Series (polaris10 LLVM 15.0.7 DRM 3.49 6.2.0-33-generic)
    direct-render: Yes
```

I have not been to reproduce this with parrarel app(t is possible that I was using it incorrectly)

https://github.com/astral-sh/ruff/assets/41945903/9205b133-8102-415d-b425-99611b14fc1e


Project to test(ruff I compiled directly from source) - [Ruff test.zip](https://github.com/astral-sh/ruff/files/12713194/Ruff.test.zip)
