### ISSUE TITLE
The uv pip install for current directory only works with editable mode

### ISSUE THREAD

**Issue by dbritto-dev** [astral-sh/ruff#10092]
* The command I invoked: `uv pip install .`
* The current Ruff settings:
```toml
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "demo"
version = "2024.02.22"
dependencies = [
  "pydantic[email]",
  "email-validator",
]
requires-python = ">=3.10"
description = "Demo"
readme = "README.md"
classifiers = [
  "Programming Language :: Python"
]
[project.optional-dependencies]
dev = ["ruff", "nox", "pytest"]
```
* The current Ruff version: 0.2.2

> **Note:** the same command with editable mode, works without any problem. Ref command: `uv pip install -e .`
