### ISSUE TITLE
File pattern syntax differs between exclude and per-file-ignores

### ISSUE THREAD

**Issue by neelmraman** [astral-sh/ruff#10147]
Hi, thanks for the work on this great project! One thing I found kind of surprising (and that doesn't seem to be explicitly mentioned in the docs anywhere) is that `exclude`/`extend-exclude` and `per-file-ignores`/`extend-per-file-ignores` seem to use a different syntax for specifying file patterns. 

Here is a fairly minimal way to reproduce on ruff v0.2.2:
1. create a new repo with this structure
```
.
├── bar_dir
│   └── a.py
├── foo_dir
│   └── a.py
└── pyproject.toml
```
where `pyproject.toml` is
```toml
[tool.ruff]
exclude = ["foo_dir"]

[tool.ruff.lint]
select = ["F"]

[tool.ruff.lint.per-file-ignores]
"bar_dir" = ["F401"]
```
and both directories have an `a.py` that looks like
```python
import os

print("hello")
```
2. run `ruff check`, and you should see an error reported for the bar_dir file but not the foo_dir file, implying the directory name alone worked as a pattern in `exclude` but not in `per-file-ignores`
3. update `pyproject.toml` so that the `per-file-ignores` is now something like `"bar_dir/**/*.py" = ["F401"]`, and run `ruff check` again, which should produce no errors.
