### ISSUE TITLE
Request: inferring `target_version` from `poetry` config

### ISSUE THREAD

**Issue by jamesbraza** [astral-sh/ruff#10175]
As of `ruff==0.2.2`, the [`target_version`](https://docs.astral.sh/ruff/settings/#target-version) can be inferrred from `pyproject.toml` package metadata in `project`.

It would be cool if, for people managing their code using `poetry`, if the `target_version` could infer from the `python` range:

```toml
[tool.poetry.dependencies]
python = ">=3.9,<3.13"
```

Thank you in advance for your consideration!
