### ISSUE TITLE
disable formatting lints (a single option)

### ISSUE THREAD

**Issue by KDruzhkin** [astral-sh/ruff#10225]
I usually enable all stable lints, and then disable some:

```toml
[tool.ruff.lint]
preview = false
select = ["ALL"]
ignore = [
   "WHAT", # comment why
   "WHAT", # comment why
   "WHAT", # comment why
]
```

Now the linter forces me to add 15 exceptions to the 'ignore' list. The ruff linter documentation says: _When using Ruff as a formatter, we recommend avoiding the following lint rules: ..._ (<https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules>)

**Can we have a single lint config option to switch off formatting lints?**

```toml
[tool.ruff.lint]
preview = false
format = false  # ☜
```
