### ISSUE TITLE
Github action documentation refers to 'options' instead of 'args'

### ISSUE THREAD

**Issue by elliot-100** [astral-sh/ruff#10246]
https://docs.astral.sh/ruff/integrations/#github-actions says:

> ruff-action accepts optional configuration parameters via with:, including:
> - version: The Ruff version to install (default: latest).
> - options: The command-line arguments to pass to Ruff (default: "check").
> - src: The source paths to pass to Ruff (default: ".").

I think 'options' here should be 'args' to match the example code:

```
- uses: chartboost/ruff-action@v1
  with:
    src: "./src"
    version: 0.0.259
    args: --select B

```

as using `options` gives:

`Warning: Unexpected input(s) 'options', valid inputs are ['args', 'src', 'version']`
