### ISSUE TITLE
Feature: file-specificity on `lint.pyupgrade.keep-runtime-typing`

### ISSUE THREAD

**Issue by tlambert03** [astral-sh/ruff#10320]
Not sure if I missed an already-possible feature, but I often find myself working in libraries that need `keep-runtime-typing = True` for only a select few files.  It would be convenient, in those cases, to enforce the rule for a subset of files with something like:

```toml
[tool.ruff.lint.pyupgrade]
keep-runtime-typing-files = ["src/subfolder/*.py"]
```

this is not currently possible, right?
