### ISSUE TITLE
SIM300: fix and check are not aligned

### ISSUE THREAD

**Issue by Borda** [astral-sh/ruff#10423]
using the latest `0.3.2` together with precommit
```yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
      - id: ruff
        args: ["--preview"]
```
and the code 
```py
def test_cloud_compute_binding():
    cloud_compute.ENABLE_MULTIPLE_WORKS_IN_NON_DEFAULT_CONTAINER = True

    assert cloud_compute._CLOUD_COMPUTE_STORE == {}
    flow = FlowCC()
    assert len(cloud_compute._CLOUD_COMPUTE_STORE) == 2
```
fixed by the first run is not accepted by the last check
```
ruff.....................................................................Failed
- hook id: ruff
- files were modified by this hook

Found 1 error (1 fixed, 0 remaining).

ruff-format..............................................................Passed
ruff.....................................................................Failed
- hook id: ruff
- exit code: 1

tests/tests_app/core/test_lightning_app.py:1119:12: SIM300 [*] Yoda conditions are discouraged, use `cloud_compute._CLOUD_COMPUTE_STORE == {}` instead
     |
1117 |     cloud_compute.ENABLE_MULTIPLE_WORKS_IN_NON_DEFAULT_CONTAINER = True
1118 | 
1119 |     assert {} == cloud_compute._CLOUD_COMPUTE_STORE
     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ SIM300
1120 |     flow = FlowCC()
1121 |     assert len(cloud_compute._CLOUD_COMPUTE_STORE) == 2
     |
     = help: Replace Yoda condition with `cloud_compute._CLOUD_COMPUTE_STORE == {}`

Found 1 error.
[*] 1 fixable with the `--fix` option.
```
