### ISSUE TITLE
Why is __main__ is considered first-party rather than stdlib ?

### ISSUE THREAD

**Issue by Avasam** [astral-sh/ruff#10549]
Edit: I got confused with #8750 and #8805 , for some reasons I though it was the other way around. Although neither the issue nor PR offers a reasoning as to why `__main__` is considered first-party rather than stdlib by default.

Here's a handful of example usage from pywin32: https://github.com/search?q=repo%3Amhammond%2Fpywin32+"import+__main__"&type=code

---

`import __main__` gets moved all the way down with first-party imports
![image](https://github.com/astral-sh/ruff/assets/1350584/4460564d-68c2-456a-bfd2-a37f3bc59d7b)

The config:
```toml
target-version = "py37"

[lint]
select = ["I"]

[lint.isort]
combine-as-imports = true
detect-same-package = false
# This forces distutils imports to always be after setuptools
extra-standard-library = ["setuptools"]
known-third-party = ["distutils"]
```
