### ISSUE TITLE
`unconventional-import-alias` (ICN001) always flags imports without an `as` clause

### ISSUE THREAD

**Issue by bardiharborow** [astral-sh/ruff#10599]
Currently `unconventional-import-alias` (ICN001) will always flag imports without an `as` clause, even if the conventional alias is the same as the module name:

```toml
[tool.ruff.lint.flake8-import-conventions.aliases]
"django.conf.settings" = "settings"
```

```py
from django.conf import settings  # ICN001 `django.conf.settings` should be imported as `settings`
from django.conf import settings as settings  # No errors
```

Instead it should detect that the module name matches the conventional alias:

```py
from django.conf import settings  # No errors
from django.conf import settings as settings  # No errors
```

(Though I realise that another rule may want to simply `from django.conf import settings as settings` to `from django.conf import settings`.)
