### ISSUE TITLE
bug: child configs that use 'select' or 'extend-select' invalidate the parent config's 'ignore' list.

### ISSUE THREAD

**Issue by Hnasar** [astral-sh/ruff#10622]
## Bug/Use-case

As someone who helps maintain a monorepo with many subprojects and child configs, I want to be able to maintain a centralized configuration of ignored rules (which projects may override with `tool.ruff.extend`). There appears to be a bug where the top-level `tool.ruff.lint.ignore` configuration _isn't honored_ whenever a child config modifies either `tool.ruff.lint.select` or `tool.ruff.lint.extend-select`. This occurs all the time, even if the child config HAS NOT overridden `tool.ruff.lint.ignore` in any way.

I (think I) understand the semantics of `ruff.extend`  alongside `lint.extend-select` and `lint.select` but the semantics of the now-combined `lint.select` create some really confusing behaviors, and mean I don't have a good way to fulfill my use-case mentioned above.

## Repro

Using ruff 0.3.4

```console
$ tree
.
└── parent
    ├── child
    │   ├── foo.py
    │   └── pyproject.toml
    └── pyproject.toml
```

```py
# child/foo.py
import os, re

"{}".format(1)
```

### 0. Parent ignores with child select

```toml
# parent/pyproject.toml
[tool.ruff]
lint.select = ["E", "UP"]
lint.ignore = ["E401", "UP032"]
```
```toml
# child/pyproject.toml
[tool.ruff]
extend = "../pyproject.toml"
lint.extend-select = ["UP"]  # also same behavior if the we use lint.select ["UP"]
```

**Observed**: 
```console
$ ruff check .
parent/child/foo.py:3:1: UP032 [*] Use f-string instead of `format` call
```

**Expected**:
```console
$ ruff check .
All checks passed!
```

* I expect that if I want the child config to invalidate the parent `ignore` list, then I have to provide my own `ignore` list. 

### 1. Parent ignores with child select and child ignore

```toml
# parent/pyproject.toml
[tool.ruff]
lint.select = ["E", "UP"]
lint.ignore = ["E401", "UP032"]
```
```toml
# child/pyproject.toml
[tool.ruff]
extend = "../pyproject.toml"
lint.extend-select = ["UP"]  # also same behavior if the we use lint.select ["UP"]
lint.ignore = ["UP032"]
```

**Observed**: 
```console
$ ruff check .
All checks passed!
```

**Expected**:
```console
$ ruff check .
parent/child/foo.py:1:1: E401 [*] Multiple imports on one line
```

* And I expect that if I provide a child `ignore` list then it fully invalidates the parent `ignore` list.

## Workarounds

Neither of these are ideal, but are some things I tried:

1. Copy and paste the parent's `lint.ignore` and keep it in sync in all the child configs. This is cumbersome to keep in sync and easy to miss things.
2. Instead of using `select` or `extend-select` in child configs, I can invert this and `ignore` all the top-level `selects` that a project wants to opt-out of. This is confusing, and also is cumbersome and easy to miss.

## Examples of fine behavior that makes sense
<details>
  <summary>Click to expand examples</summary>
  

### 2. No ignores

```toml
# parent/pyproject.toml
[tool.ruff]
lint.select = ["E", "UP"]
```

```toml
# child/pyproject.toml
[tool.ruff]
extend = "../pyproject.toml"
```

```console
$ ruff  check .
parent/child/foo.py:1:1: E401 [*] Multiple imports on one line
parent/child/foo.py:3:1: UP032 [*] Use f-string instead of `format` call
```

### 3. Child select
```toml
# parent/pyproject.toml
[tool.ruff]
lint.select = ["E", "UP"]
```
```toml
# child/pyproject.toml
[tool.ruff]
extend = "../pyproject.toml"
lint.select = ["UP"]
```
```console
$ ruff  check .
parent/child/foo.py:3:1: UP032 [*] Use f-string instead of `format` call
```

### 4. Child extend-select

```toml
# parent/pyproject.toml
[tool.ruff]
lint.select = ["E", "UP"]
```
```toml
# child/pyproject.toml
[tool.ruff]
extend = "../pyproject.toml"
lint.extend-select = ["UP"]
```

```console
$ ruff  check .
parent/child/foo.py:1:1: E401 [*] Multiple imports on one line
parent/child/foo.py:3:1: UP032 [*] Use f-string instead of `format` call
```

### 5. Parent ignores without any child select

```toml
# parent/pyproject.toml
[tool.ruff]
lint.select = ["E", "UP"]
lint.ignore = ["E401", "UP032"]
```
```toml
# child/pyproject.toml
[tool.ruff]
extend = "../pyproject.toml"
```
```console
ruff  check .
All checks passed!
```
</details>
