### ISSUE TITLE
`ICN003`: Allow banning all `from` stdlib imports

### ISSUE THREAD

**Issue by Grub4K** [astral-sh/ruff#10664]
Our project decided to no longer allow stdlib imports with `from` due to potentially clashing naming causing confusion.
We are currently resorting to including every stdlib in the `flake8-import-conventions` `banned-from` setting:
```toml
[tool.ruff.lint.flake8-import-conventions]
banned-from = ["abc", "aifc", "antigravity", "argparse", "array", "ast", "asynchat", "asyncio", "asyncore", "atexit", "..."]
```
However this is very cumbersome. Is there a possiblity of referencing all stdlib modules? A shortcut like this could perhaps also be used for different importing settings.

I've searched for `ICN003`, `banned-from` and `banned-import-from`, but could not find anything related.
