### ISSUE TITLE
W292 does not trigger even in preview mode

### ISSUE THREAD

**Issue by yrahul3910** [astral-sh/ruff#10677]
I want to configure Ruff so that it ensures one empty newline at the end of each file in Python. This should be `W292` (`missing-newline-at-end-of-file`), and is implemented in preview mode (so my understanding goes from #2402). My current `pyproject.toml` is below.

```toml
[tool.ruff]
exclude = [
    ".DS_Store",
    ".git",
    "__pycache__",
    ".mypy_cache",
    ".ruff_cache"
]

line-length = 120
target-version = "py312"

[tool.ruff.lint]
preview = true
select = ["E", "W", "F", "I001", "RUF002", "RUF100", "RUF013", "RUF010", "RUF200"]
extend-select = ["W292"]

[tool.ruff.lint.isort]
lines-after-imports = 2
lines-between-types = 1
section-order = ["future", "standard-library", "first-party", "local-folder", "third-party"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"

[tool.ruff.lint.pycodestyle]
max-doc-length = 120
```

A MWE is fairly straightforward:

```sh
echo "print('Hello World!')" >> main.py
```

And then running `ruff check .` (even with `--isolated`) yields, "All checks passed!". I double-checked, and `wc -l` gives me 1 line in `main.py`. I am using Ruff 0.3.4, installed via pip, on macOS Sonoma 14.4.1.
