### ISSUE TITLE
`exclude` under `[tool.ruff.lint]` does not exclude directory

### ISSUE THREAD

**Issue by ajhynes7** [astral-sh/ruff#10878]
# Description

I've found that `ruff check` doesn't exclude a directory, although the name is included in the `exclude` list under `[tool.ruff.lint]` in `pyproject.toml`.

From the ruff docs, in [Settings/lint/exclude](https://docs.astral.sh/ruff/settings/#lint_exclude):

> Exclusions are based on globs, and can be either:
> - Single-path patterns, like `.mypy_cache` (to exclude any directory named `.mypy_cache` in the tree), `foo.py` (to exclude any file named `foo.py`), or `foo_*.py` (to exclude any file matching `foo_*.py`).

However, I've found that specifying the directory name doesn't work. 

# Environment
```bash
$  ruff --version
ruff 0.3.5
```

# Reproduction
I reproduced this with a minimal project.

Project contents:
```bash       
$ tree
.
├── dir1
│   └── foo.py
├── poetry.lock
└── pyproject.toml
```

`foo.py`:
```py
# foo.py

def foo():
    x = 1
```

`pyproject.toml`:
```toml

[tool.poetry]
name = "foo"
authors = []
description = ""
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
ruff = "^0.3.5"

[tool.ruff.lint]
exclude = ["dir1"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

Command:
```bash
$  ruff check .
dir1/foo.py:2:5: F841 Local variable `x` is assigned to but never used
Found 1 error.
No fixes available (1 hidden fix can be enabled with the `--unsafe-fixes` option).
```

# Notes
If I use `exclude` in the top-level `[tool.ruff]` section instead, the directory is excluded as expected.

```toml
[tool.ruff]
exclude = ["dir1"]
```

```bash
$  ruff check .
All checks passed!
```

I can also get the directory excluded if I put a wildcard at the end. But according to the docs, the directory name alone should suffice.

```toml
[tool.ruff.lint]
exclude = ["dir1/*"]
```

```bash
$  ruff check .
All checks passed!
```
