### ISSUE TITLE
It's not possible to remove unused import AND sort them

### ISSUE THREAD

**Issue by rruiter87** [astral-sh/ruff#10882]
I'm using ruff with the following pre-commit. My goal is to have sorted imports (I001) and unused ones are removed (F401). 

```yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.5
    hooks:
      # Run the linter.
      - id: ruff
        # --select I sorts imports
        args: [ --fix, --select, I  ]
      # Run the formatter.
      - id: ruff-format
```

With `args: [ --fix, --select, I  ]` it sorts the imports, but it doesn't remove unused ones. With `args: [ --fix ]` it doesn't sort, but removed unused imports. 

Is this intended behavior? And is there a way to get both to work?
