### ISSUE TITLE
Format suppression is ignored for imports

### ISSUE THREAD

**Issue by b-phi** [astral-sh/ruff#10881]
I have a long import line that I'd like to custom format to avoid exceeding the configured line length. Neither `# fmt: skip` or `# fmt: off` seem to prevent ruff from reformatting the line. I confirmed that format suppression does work for other statements in the file.

Input
```python
x =           2  # fmt: skip
from my.very_very_very_very_very_very_very_long_package\
    import my_very_very_very_very_very_very_long_name  # fmt: skip

# or

# fmt: off
x =           2
from my.very_very_very_very_very_very_very_long_package\
    import my_very_very_very_very_very_very_long_name
# fmt: on
```

Output
```python
x =           2  # fmt: skip
from my.very_very_very_very_very_very_very_long_package import (
    my_very_very_very_very_very_very_long_name
)

# or

# fmt: off
x =           2
from my.very_very_very_very_very_very_very_long_package import (
    my_very_very_very_very_very_very_long_name
)
# fmt: on
```

Version: 0.3.5

Config
```yaml
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.5
  hooks:
    - id: ruff-format
    - id: ruff
```

```toml
[tool.ruff]
line-length = 79
fix = true

[tool.ruff.format]
quote-style = 'single'

[tool.ruff.lint]
extend-select = ['E501', 'I']
```
