### ISSUE TITLE
`RUF100` error despite listed in `per-file-ignores` 

### ISSUE THREAD

**Issue by pjonsson** [astral-sh/ruff#10906]
Using Ruff 0.3.7, I tried to select the "RUF" category, and got a `RUF100` error. Adding the file to `per-file-ignores` in pyproject.toml seems to have no effect. The section works for other files/rules in the project, I'm even using it for `RUF005`.

I have not had the RUF category enabled with previous versions, so I do not know if it this is a regression in Ruff. I searched a bit in the issues, not sure if #6385 or #9300 are related to my problem.

Minimizing the file to this:
```python
class Ruf100:
    def to_dict(self):
        return {
            "really_really_long_key": self.really_really_long_designator(),  # noqa
        }
```
and putting it in ruf100.py preserves the error:
```
ruf100.py:4:78: RUF100 [*] Unused blanket `noqa` directive
```
I would be happy to remove the noqa directive, but Flake8 fails on the real code if I remove it.

Here are what I believe the relevant parts of pyproject.toml are, please let me know if you need more:
```toml
[tool.ruff]
src = ["src", "tests"]
target-version = "py310"

[tool.ruff.lint]
select = ["RUF"]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"src/project/cli.py" = ["UP007", "B008"]

# TO BE FIXED
"src/project/subdir/file.py" = ["RUF015"]
"src/project/otherdir/file2.py" = ["RUF100"]
"ruf100.py" = ["RUF100"]
```
