### ISSUE TITLE
Add `honor-case-in-force-sorted-sections` flag for `isort`

### ISSUE THREAD

**Issue by serjflint** [astral-sh/ruff#10928]
Hi!

ruff 0.3.4

I am trying to sort imports like `ruff check package/module.py --fix-only`

```python
from typing import cast
from typing import Union
```

my config

```toml
[tool.ruff.lint]
select = ["I"]

[tool.ruff.lint.isort]
case-sensitive = true
force-single-line = true
force-sort-within-sections = true
order-by-type = false
```

I get 

```python
from typing import Union
from typing import cast
```

Instead of the file staying the same.

Please add the option from isort
https://pycqa.github.io/isort/docs/configuration/options.html#honor-case-in-force-sorted-sections
