### ISSUE TITLE
`ruff server` add setup guide for helix editor

### ISSUE THREAD

**Issue by bluthej** [astral-sh/ruff#11027]
I'm very excited about the new Ruff LSP, and I would like to try it out in Helix, my editor of choice :)

I did not have a ton of time to look at the config yet but I started playing around with it and I believe the config should start with something like this:

```toml
[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]
```

Then the language server should be added alongside whatever other server you like to use (guess which one I use):

```toml
[[language]]
name = "python"
language-servers = ["ruff", "pylsp"]
```

I haven't really had a ton of success for now with server-specific configs (like the ones in the [neovim setup](https://github.com/astral-sh/ruff/blob/main/crates/ruff_server/docs/setup/NEOVIM.md)), so a dedicated setup guide would be much appreciated :) 
Or really any pointer on the setup!
