### ISSUE TITLE
FURB118 static method "false positive"

### ISSUE THREAD

**Issue by Rhinopitheque** [astral-sh/ruff#11045]
The rule FURB118 detects "false positives" on classes methods.

Keywords: "FURB118", "method"
```
@staticmethod 
    def get_postal_code(area_code: str) -> str:
        return area_code[:5]
```
Ruff v0.4.0 used with pre-commit hook:
```
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.0
    hooks:
      - id: ruff
```
