### ISSUE TITLE
[UP006/7] The `target-version` configuration is not applied to `*.pyi`

### ISSUE THREAD

**Issue by Starry-OvO** [astral-sh/ruff#11064]
## Introduction

For `UP006/7`, The `target-version` configuration is not applied to `*.pyi`. I create a [repo](https://github.com/Starry-OvO/ruff-UP4pyi-demo) to reproduce this issue.

## Version

Run `ruff -V`

Get 

```log
ruff 0.4.1
```

## Configuration

```toml
[tool.ruff]
target-version = "py38"

[tool.ruff.lint]
select = ["UP"]
```

## To Reproduce

Follow the [demo](https://github.com/Starry-OvO/ruff-UP4pyi-demo) or the steps below.

Add `foo.pyi` to the cwd.

```python
from typing import List, Union

def UP006() -> List[int]: ...
def UP007(a: bool) -> Union[str, int]: ...
```

Add `foo.py` to the cwd.

```python
from typing import List, Union


def UP006() -> List[int]:
    return [1, 2, 3]


def UP007(a: bool) -> Union[str, int]:
    if a:
        return "hello ruff"
    else:
        return 42
```

Add `pyproject.toml` to the cwd.

```toml
[project]
name = "ruff-UP4pyi-demo"
version = "0.1.0"
description = "Demo for the bug within ruff UP006/7 rules"
authors = [{ name = "Starry-OvO", email = "starry.qvq@gmail.com" }]
dependencies = []
readme = "README.md"
requires-python = ">=3.8,<3.13"

[tool.rye]
managed = true
virtual = true

[tool.ruff]
target-version = "py38"

[tool.ruff.lint]
select = ["UP"]
```

## Behaviour

Run `ruff check .`

Get

```log
foo.pyi:3:16: UP006 Use `list` instead of `List` for type annotation
foo.pyi:4:23: UP007 Use `X | Y` for type annotations
Found 2 errors.
No fixes available (2 hidden fixes can be enabled with the `--unsafe-fixes` option).
```

## Expect Behaviour

Run `ruff check .`

Get

```log
All checks passed!
```
