### ISSUE TITLE
`W505` reported as `E501` a.k.a doc-line-too-long

### ISSUE THREAD

**Issue by Borda** [astral-sh/ruff#11100]
it could be just my wrong understanding or expectations but running formatting on https://github.com/unit8co/darts/pull/2341, and they would like to make 88 line-length for code only and docstring differently, so I found [`W505`](https://docs.astral.sh/ruff/rules/doc-line-too-long/)
which I wanted to ignore, but it turned out it is not reported but `E501`. Well, `E501` is correct, but it is a superset, and `W505` would better describe the case...

using:
```yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
```
