### ISSUE TITLE
Q000 is not enforced with  `inline-quotes = "single"`

### ISSUE THREAD

**Issue by Borda** [astral-sh/ruff#11209]
following my comment in https://github.com/astral-sh/ruff/issues/7834#issuecomment-2083830199 and https://github.com/OpenDevin/OpenDevin/pull/1425#discussion_r1582056596

We are using `v0.4.1` with preco-commit and setting single-quotes but it is not enforced...
This is our config:
```toml
[lint]
select = [
    "E", "W", "F",
    "Q",
]

[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[format]
quote-style = "single"
```
and this is the sample string which is untouched
```py
logger.info(
    f"Connecting to {username}@{hostname} via ssh. If you encounter any issues, you can try `ssh -v -p {self._ssh_port} {username}@{hostname}` with the password '{self._ssh_password}' and report the issue on GitHub."
)
```
