### ISSUE TITLE
`ruff server` first-party libraries get categorized as third-party

### ISSUE THREAD

**Issue by bluthej** [astral-sh/ruff#11214]
Keywords: I001, Organize imports, first-party

Ruff version : 0.4.2

If I'm not mistaken, `ruff server` currently treats first-party libraries like they're third-party libraries, which is not the case for `ruff-lsp`.

Here is a minimal setup to reproduce this:
- Create a new project with the following layout:
```shell
.
├── pyproject.toml
└── src
     └── hello_world
         ├── __init__.py
         ├── module.py
         └── other_module.py
```
with these contents:
<details><summary>pyproject.toml</summary>
<p>

```toml
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hello-world"
version = "0.0.1"
dependencies = [
  "numpy"
]

[tool.ruff]
lint.extend-select = ["I"]
```

</p>
</details> 

<details><summary>module.py</summary>
<p>

```python
hello = "hello world"
```

</p>
</details> 

<details><summary>other_module.py</summary>
<p>

```python
from pathlib import Path

from numpy.linalg import norm

from hello_world.module import hello
```

</p>
</details> 

- Then run `ruff-lsp` in an editor => this should not lint the import order, just like doing `ruff check .` doesn't say anything about import order
- Then run `ruff server` in an editor => now there should be an `Organize import` lint, and if you apply it, it should bring the `hello_world` import just above the `numpy` import, which is not the expected behavior
