### ISSUE TITLE
ruff config custom filename

### ISSUE THREAD

**Issue by padrepitufo** [astral-sh/ruff#11344]
When using the `--config` option in `.pre-commit-config.yaml` like so:

```
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff
        name: pycln api
        files: ^api/
        args: ["--config=./pyproject.ruff.toml"]
```

or when running the command locally with:

```
ruff --config pyproject.ruff.toml
```

 and supplying a pyproject formatted file with a name other than `pyproject.toml` (as shown above), ruff will *not* recognize the file as a pyproject formatted file (it will assume it is a malformed `.ruff.toml` file) and give errors like so:

```
  Cause: TOML parse error at line 1, column 1
  |
1 | [tool.ruff]
  | ^
unknown field `tool`
```

### Use Case
Why oh why am I splitting up my pyproject.toml files? The team I'm working with generally does this when the section gets long within `pyproject.toml`.   While it is nice to keep all the configurations in one file, it is also nice to keep all configurations in the same format and that is what I'm aiming for.

Is this something that could be supported by the ruff community?

### Context
command: `ruff --config pyproject.ruff.toml`
ruff: v0.4.3
pre-commit: 3.7.0
