### ISSUE TITLE
Feature: Replacements for pre-commit rules

### ISSUE THREAD

**Issue by glensc** [astral-sh/ruff#11380]
pre-commit is rather slow, so I'm looking for to replace this all:

```yml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: destroyed-symlinks
      - id: mixed-line-ending
```

Source: https://github.com/Taxel/PlexTraktSync/blob/ab773cc0b3dc1c3c7efbf8509e5627d1dba1d3dd/.pre-commit-config.yaml#L5-L21
