### ISSUE TITLE
Ruff gives unhelpful error message for all commands when pyproject.toml is invalid

### ISSUE THREAD

**Issue by mscheifer** [astral-sh/ruff#11481]
When my `pyproject.toml` file is invalid, every `ruff` command gives the same somewhat confusing error message.
```shell
$ poetry run ruff check

Invalid statement (at line 9, column 1)
$ poetry run ruff --help

Invalid statement (at line 9, column 1)
$ poetry run ruff --version

Invalid statement (at line 9, column 1)
$ poetry run ruff server --preview

Invalid statement (at line 9, column 1)
```

My `pyproject.toml` (reduced down for simplicity) looks like:
```toml
[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.4"
<<<<<<< HEAD
hypothesis = "^6.102.4"
=======
pytest = "^8.2.1"
>>>>>>> main

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

The error message doesn't make it clear that this is caused by the`pyproject.toml` file. I think the message should say
```
Failed to parse pyproject.toml. Aborting
Invalid statement (at line 9, column 1)
```
or something.

Less importantly, it would be nice if some commands like `--help` and `--version` still worked even when it can't parse `pyproject.toml`.
