### ISSUE TITLE
docstring-code-format fails with semicolons

### ISSUE THREAD

**Issue by JasonGrace2282** [astral-sh/ruff#11480]
## Example
```py
"""
>>> l = []
>>> l.append(3); l
[3]
"""
```
## Expected
"""
>>> l = []
>>> l.append(3)
>>> l
[3]
"""

## Result
"""
>>> l = []
>>> l.append(3)
... l
[3]
"""

## Reproduce:
```toml
[tool.ruff.format]
docstring-code-format = true
```
And run `ruff format` on the file.
