### ISSUE TITLE
`ruff server` in `v0.4.5` doesn't consider the configuration setting in Neovim

### ISSUE THREAD

**Issue by a1401358759** [astral-sh/ruff#11507]
When I updated to version 0.4.5, the E30* checks all failed and nothing changed in my configuration

my pyproject.toml
```toml
[tool.ruff]
preview = true
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 120
indent-width = 4

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F", "I001"]
ignore = ["E402","E501","N802","N803","N806","N801","N813","N815","N816","RUF001","RUF002","RUF003","RUF012","ARG001"]
extend-select = ["E", "N", "W", "ARG", "RUF"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
```

my ruff config
```lua
  init_options = {
    filetypes = { "python" },
    single_file_support = true,
    cmd = { "ruff", "server", "--preview" },
    settings = {
      configuration = "~/.config/nvim/pyproject.toml",
    },
  },
```

**Comment by dhruvmanila** [comment]
Can you provide a minimal code snippet on which it's failing? And, just to confirm, by "failing" do you mean that the v0.4.4 wasn't raising any violations but v0.4.5 does?

**Comment by a1401358759** [comment]
@dhruvmanila 
![image](https://github.com/astral-sh/ruff/assets/15830146/7f0af8ac-d4c5-4e84-9ea3-cd0c8ecc4cc0)
I'm sorry, I wasn't accurate in my description. It's not a failure, it's a non-effect.

**Comment by snowsignal** [comment]
I haven't been able to reproduce this issue. The `pyproject.toml` you put in the issue is the one in `~/.config/nvim`, right? Do you have any local `.toml` configuration files?

**Comment by a1401358759** [comment]
@snowsignal 

<img width="363" alt="image" src="https://github.com/astral-sh/ruff/assets/15830146/2f49f236-7178-4adc-a7aa-688b61bfeb01">

<img width="304" alt="image" src="https://github.com/astral-sh/ruff/assets/15830146/bf9e89e8-27ce-40ca-9aae-64746f498094">

I don't have any local `.toml` configuration files

**Comment by dhruvmanila** [comment]
@a1401358759 You don't seem to have enabled the `E30` checks in your lint config. Can you update and check if it works with `E30` in your `select`?

```toml
[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E30", "E4", "E7", "E9", "F", "I001"]
```
