### ISSUE TITLE
`lint.per-file-ignores` option is ignored by the new language server

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/ruff#11751]
when enabling the new `ruff.nativeServer` setting in vscode, it seems to ignore `tool.ruff.lint.per-file-ignores`
```toml
# pyproject.toml

[tool.ruff.lint]
extend-select = ["S101"]
[tool.ruff.lint.per-file-ignores]
"tests/**/.py" = ["S101"]
```
```jsonc
// .vscode/settings.json

{
  "ruff.nativeServer": true
}
```

![image](https://github.com/astral-sh/ruff/assets/57028336/b773846b-0b02-4f01-b41d-65baee0d2ebf)
