### ISSUE TITLE
`Args:` section not correctly formatted when no description is provided

### ISSUE THREAD

**Issue by antoinebrl** [astral-sh/ruff#11904]
Hello,

I stumbled upon this bug when trying to add `pydocstyle` rules using the Google docstring convention. The `Args:` section is not correctly identified and therefore formatted when no description is provided. For example, this code
```python
class MyClass:
    """Short Summary.
    
    Long description.
    """

    def __init__(self, a, b):
        """
        Args:
            a: first argument.
            b: second argument.
        """
        self.a = a
        self.b = a
```
if formatted to this:
```python
class MyClass:
    """Short Summary.
    
    Long description.
    """

    def __init__(self, a, b):
        """Args:
        a: first argument.
        b: second argument.
        """
        self.a = a
        self.b = a
```

The command I used is `ruff check --config ../ruff.toml --fix ruff-d212.py` and the config is below:
```toml
target-version = "py310"
line-length = 120

[format]
docstring-code-format = true
docstring-code-line-length = 89
skip-magic-trailing-comma = true

[lint]
preview = true
select = [
    "D",        # pydocstyle
]

[lint.pydocstyle]
convention = "google"
```

Note that the `--fix` resolved D212 but not D205, which make me to think the section is not correctly identified:
```
ruff-d212.py:8:9: D205 1 blank line required between summary line and description
ruff-d212.py:8:9: D212 [*] Multi-line docstring summary should start at the first line
```
