### ISSUE TITLE
`ruff format` not formatting the files recursively but `ruff format folder/folder1/folder2/folder3` works

### ISSUE THREAD

**Issue by vigneshmanick** [astral-sh/ruff#12146]
This is a weird issue that i have encountered. I cannot also reproduce it in a similar folder structure outside the current project. I'll try to describe what happens.

I have a python project setup using `pyproject.toml` and the ruff configuration is as follows

```toml

[tool.pytest.ini_options]
testpaths = [
  "testSuite",
]

[tool.ruff]
preview = false

exclude = [
  "src/mymodule/somefolder/anotherfolder",
]

[tool.ruff.lint]
select = ["E", "F", "W", "NPY", "RUF", "I"]
ignore = ["E722", "RUF012", "E111", "E114", "E117", "E501", "W191", "E203"]

[tool.ruff.lint.per-file-ignores]
# Ignore `E402` (import violations) in all `__init__.py` files
"__init__.py" = ["E402"]

```

#### Issue

The files inside `testSuite` are not fomatted when running `ruff format` from the top level folder. 

If i run `ruff format testSuite/path/to/folder/inside/` then it works but only if the path supplied is the last level in the tree. See output below. Note how the last command formats the files but the first 2 don't.

```bash
(myenv) user@node123 project>ruff format .
1001 files left unchanged
(myenv) user@node123 project>ruff format testSuite/testCases/abcutTests/
67 files left unchanged
(myenv) user@node123 project>ruff format testSuite/testCases/abcutTests/HamstrTest/
6 files reformatted, 20 files left unchanged
```

### System info
* ruff version: 0.4.4
* python: 3.11.4
* system: Redhat-7.9

Any pointers here on what exactly i am doing wrong would be helpful. 

Thanks!
