### ISSUE TITLE
[flake8-bugbear] Avoid false positive for usage `return None` (B901)

### ISSUE THREAD

**Issue by f4rk4sh** [astral-sh/ruff#12156]
A minimal code snippet that reproduces the bug is almost the same as [here](https://github.com/astral-sh/ruff/commit/312f6640b837eb1189748980707cfed70d1f5ffb#diff-3da9dc4c996fc465b80db3e323994049105aa08d73a56f50a4991481408f90e4R16) but with explicit `return None`:

```python
def not_broken():
        if True:
            return None

        yield 3
        yield 2
        yield 1
```

The false positive:

```sh
B901 Using `yield` and `return {value}` in a generator function can lead to confusing behavior
   |
64 |     def not_broken():
65 |         if True:
66 |             return None
   |             ^^^^^^^^^^^ B901
67 | 
68 |         yield 3
   |

Found 1 error.
```

The command invoked:

```yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix", "--preview"]
```
