### ISSUE TITLE
Disable `ANN001` for arguments with defaults

### ISSUE THREAD

**Issue by arichr** [astral-sh/ruff#12223]
I would like to proposal a configuration option to disable `ANN001` if a function argument has a default value. Consider the following example:
```python
def foo(a: int, b: float, c=False) -> str:
    ...
```
Checking this file with Ruff reports:
```console
$ ruff check foo.py
foo.py:1:27: ANN001 Missing type annotation for function argument `c`
Found 1 error.
```
With the option enabled, this function would not report an error.

**Additional information:**
* I searched for existing issues using *implicit argument type* keywords.
* Ruff version: `ruff 0.5.1`
* `ruff.toml`:
```toml
output-format = "concise"

[lint]
preview = true
explicit-preview-rules = true
select = ["ANN001"]
```
