### ISSUE TITLE
RUF013 does not check usage of implicit None in class constructors

### ISSUE THREAD

**Issue by mikeweltevrede** [astral-sh/ruff#12403]
I noticed that rule [RUF013](https://docs.astral.sh/ruff/rules/implicit-optional/) did not check usage of implicit optionals in the class constructors `__init__()`. I would expect to see `RUF013 PEP 484 prohibits implicit 'Optional'`, but instead, it passes the checks.

# List of keywords you searched for before creating this issue
- RUF013
- Optional

# A minimal code snippet that reproduces the bug
```python
class MyClass:
    def __init__(self, a: int = None): ...
```

# The command you invoked
- `ruff check --select RUF013`
- `pre-commit run --all-files`

# The current Ruff settings
```toml
[tool.ruff]
line-length = 120
target-version = "py39"

[tool.ruff.lint]
extend-select = [
    ...,
    "RUF",
    ...,
]
```

# The current Ruff version
`0.5.3` but also tried with earlier versions `0.3.0` and `0.4.0`.
