### ISSUE TITLE
Inconsistent removal of whitespace around operators

### ISSUE THREAD

**Issue by robin-weiland** [astral-sh/ruff#12425]
In the snippet below, there are two occurrences of the `**`-operator.
Following pep8, I added spaces around them.

Now I can either run pre-commit or `ruff format` directly and the only issue it finds and corrects are the spaces around the first power operator, which it removes. Notably, the ones in the Exception are left as they are.

Is there any reason I am unaware of for this inconsistency?
Also, if the removal of spaces is indeed the intended behavior here, is there a way to ignore this?
I could only find rules to explicitly ignore missing whitespace (e.g., E225) not vice versa.

## snippet

```python
if not (0 <= value < (2 ** self.size)):
    raise ValueError(
        f'Value "{value}" must be between 0 and {(2 ** self.size) - 1} with size {size}!'
    )
```

## ruff settings

```toml
[tool.ruff]
exclude = [
    ".git",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "dist",
]
line-length = 88
indent-width = 4
target-version = "py311"

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
```

### pre-commit-config.yaml

```yaml
# ...

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
      - id: ruff
      - id: ruff-format

# ...
```

## ruff version

ruff 0.4.10

## environment

win11 23H2
Python 3.11.5 (tags/v3.11.5:cce6ba9) 64 bit
Poetry (version 1.8.3)
pre-commit 3.7.1

---

keywords: whitespace-around-operator, E225
