### ISSUE TITLE
[Infinite loop] for `required-imports` with more than one argument

### ISSUE THREAD

**Issue by Anselmoo** [astral-sh/ruff#12560]
It looks like a `required-import` fails for more than one import. Would this in general possible to import more than _required_ import?

```toml
required-imports = [
    "from __future__ import annotations",
    "import numpy as np",
]
```

and get:

> the contents of `mypackage/data_model.py`, the rule codes I002, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

<details><summary>Complete setup</summary>
<p>

```toml
[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py39"
lint.select = [
    "ALL",
]
fix = true
lint.fixable = [
    "ALL",
]
lint.ignore = [
    "ANN101",  # annotations for self
    "ARG002",  # unused argument
    "PLR0913", # too many arguments
    "PD008",   # missing pandas
    "ISC001",  # single-line-implicit-string-concatenation 
    "COM812",  # missing trailing-comma"
]
src = [
    "mypackage",
]
exclude = [
    "mypackage/test",
    "mypackage/core",
]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 60
indent-style = "space"
preview = true
quote-style = "double"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.ruff.lint.per-file-ignores]
"mypackage/test/test_*.py" = [
    "PLR2004", # magic value comparison
    "S101",    # use of assert detected
    "TCH002",  # third party import (for pytest)
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
known-first-party = [
    "mypackage",
]
force-single-line = true
lines-between-types = 1
lines-after-imports = 2
known-third-party = [
    "poetry.core",
]
required-imports = [
    "from __future__ import annotations",
    "import numpy as np",
]
```

</p>
</details>
