### ISSUE TITLE
Multiline-quotes on docstrings

### ISSUE THREAD

**Issue by karolyi** [astral-sh/ruff#12631]
Hello,

I started experimenting around with ruff to see if it can suit my needs and coding style. I've dropped it and went back to pylsp because while I can enforce strings to be single-quoted (docstrings included), I can't enforce that _multiline docstrings_ be double-quoted, as in:

```python
def single_docstring():
   'some docstring that lies in a single line'

def multiline_docstring():
    """
    Some docstring
    that for some reason,
    will have to be broken into multiple lines.
    """
```

It seems that with the current configurable options that is not to be achieved. The only ones I could find about this current state are:
```toml
[lint.flake8-quotes]
docstring-quotes = 'single'
multiline-quotes = 'double'
inline-quotes = 'single'
```

And we haven't even talked about the autoformatting part.

I have some more qualms but this is the single most one that made me drop ruff, unfortunately. Let me know if or when this is/will-be achieavable.
