### ISSUE TITLE
`RUF031` (`incorrectly-parenthesized-tuple-in-subscript`) - false positive on types

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/ruff#12773]
```toml
# ruff.toml
[lint.ruff]
parenthesize-tuple-in-subscript = true
```
```py
foo = dict[str, str] = {} # error: Use parentheses for tuples in subscripts.
```

subscripts have a completely different meaning in type annotations, and the fact that the arguments to `dict` are a tuple is an implementation detail of the syntax, so i don't think this rule should apply to them.
