### ISSUE TITLE
CPY: no support for Jupyter Notebook files

### ISSUE THREAD

**Issue by adamjstewart** [astral-sh/ruff#12802]
### Keywords

flake8-copyright, CPY, Jupyter Notebook, .ipynb

### Steps to reproduce

Using the following `pyproject.toml`:
```toml
[tool.ruff]
extend-include = ["*.ipynb"]

[tool.ruff.lint]
extend-select = ["CPY"]
preview = true

[tool.ruff.lint.flake8-copyright]
author = "..."
```
if I run `ruff check` on my repo, all files pass except the Jupyter Notebook files. This is because ruff only checks the first 4096 bytes of the file, whereas the copyright may be in the first cell of the notebook farther below.

### Version

Ruff 0.5.7

### Solution

We would likely need to check more bytes, or allow the total number of bytes to be set on a per-repo or per-file basis. For now, the only workaround is to disable CPY on Jupyter Notebooks.

**Comment by MichaReiser** [comment]
Hmm, the notebook code should run on the concatenated contend of all python cells. Could you share a notebook with us that demonstrates the issue?

**Comment by adamjstewart** [comment]
Try this one: https://github.com/microsoft/torchgeo/blob/v0.5.2/docs/tutorials/getting_started.ipynb

You'll need:
```toml
[tool.ruff.lint.flake8-copyright]
author = "Microsoft Corporation"
notice-rgx = "Copyright \\(c\\)"
```

**Comment by charliermarsh** [comment]
Thanks, I'll try to reproduce.

**Comment by charliermarsh** [comment]
Hmm, I ran this locally and got:

```
getting_started.ipynb:cell 4:1:1: CPY001 Missing copyright notice at top of file
```

My `pyproject.toml` looks like:

```toml
[tool.ruff]
extend-include = ["*.ipynb"]

[tool.ruff.lint]
extend-select = ["CPY"]
preview = true

[tool.ruff.lint.flake8-copyright]
author = "Microsoft Corporation"
notice-rgx = "Copyright \\(c\\)"
```
