### ISSUE TITLE
`ruff server` hangs when performing "code actions" in Helix

### ISSUE THREAD

**Issue by schlich** [astral-sh/ruff#12915]
Might be related to [Issue #416](https://github.com/astral-sh/ruff-lsp/issues/416) in `ruff-lsp`, particularly @ssmsossah's comment [here](https://github.com/astral-sh/ruff-lsp/issues/416#issuecomment-2143850769) that the same thing is happening in NeoVim.

Running `ruff server` in Helix. Health checks with `hx --health python` all pass.

Helix 24.7
ruff 0.6.0
`protocol error: InternalError: failed to deserialize diagnostic data: missing field 'range'`

```toml
[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "-"]}
language-servers = ["ruff", "pyright", "pylsp"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff"
args = ["server"]
```

**Comment by schlich** [comment]
Welp, looks like I just rubber-ducked my way out of this one.  dunno how that misconfig slipped in but changing `args = ["server"]` to `config = { settings = { args = ["server"] } }` as suggested in the helix docs fixed the issue... closing.

**Comment by dhruvmanila** [comment]
I'm a bit confused here. What was the exact change? The `args = ["server"]` should be correct. Can you provide the docs reference for this?

**Comment by schlich** [comment]
@dhruvmanila  it's [here](https://github.com/helix-editor/helix/wiki/Language-Server-Configurations#python---ruff)

**Comment by dhruvmanila** [comment]
That's weird because their [documentation](https://docs.helix-editor.com/languages.html#language-server-configuration) mentions the use of `args`:

> `args` | A list of arguments to pass to the language server binary

while, the `config` key is actually the initialization options which is different.

I'll need to try this out.

**Comment by dhruvmanila** [comment]
I'm getting code actions:

<img width="1727" alt="Screenshot 2024-08-16 at 14 39 26" src="https://github.com/user-attachments/assets/d3680df5-9fb4-44a3-9492-d369e5e61094">

Using the following config:
```toml
[[language]]
name = "python"
language-servers = ["ruff", "pyright"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]
```
