### ISSUE TITLE
PyUpgrade rule UP007 do not work on forward reference string types

### ISSUE THREAD

**Issue by goodspark** [astral-sh/ruff#12945]
Keywords: forward reference, pyupgrade, UP007

Python 3.12, also 3.10
Ruff 0.6.1
Command: `ruff check .`

Code:

Python file
```py
x: Optional['Something']  # expect UP007 to trigger here -> x: 'Something | None'
y: Union[int, 'Something']  # expect UP007 to trigger here -> y: 'Something | int'
x2: Optional[Something]  # correctly caught by UP007
y2: Union[int, Something]  # correctly caught by UP007
class Something:
  pass
```

pyproject.toml
```toml
[project]
# As long as this is >=3.10 or any subset, like ==3.10, this bug will occur.
requires-python = ">=3.12"

[tool.ruff.lint]
extend-select = ["UP"]
extend-safe-fixes = ["UP007"]
```
