### ISSUE TITLE
Invalid JSON schema on ruff lint settings

### ISSUE THREAD

**Issue by mash180sx** [astral-sh/ruff#13003]
Is there any reason I get this error in my pyproject.toml file, using VS Code?
It seems it's related to the corresponding JSON Schema.

```toml

[tool.ruff]
line-length = 88
target-version = "py312"
src = ["src/backend"]

[tool.ruff.lint]
ignore = []
select = ["E", "F", "I", "N"]
per-file-ignores = {"__init__.py" = ["F401"]}
isort = {known_first_party = ["app"]}
```

<img width="568" alt="スクリーンショット 2024-08-20 15 58 22" src="https://github.com/user-attachments/assets/09b0d823-ccaf-4fb7-9175-18783a961c4e">

<img width="670" alt="スクリーンショット 2024-08-20 16 02 37" src="https://github.com/user-attachments/assets/be4ec025-ed66-4a6d-b851-807e46a4f286">
