### ISSUE TITLE
Ruff toml with `extend` doesn't apply the rules

### ISSUE THREAD

**Issue by rogier-stegeman** [astral-sh/ruff#13232]
I looked for: "extend", "extend configuration".

Version: 0.6.3

**Situation**
```py
#test.py
def f(a):
    return a
```

And 
```toml
#ruff.toml
extend  = "./ruff.2.toml"
[lint]
select = []
ignore = []
```

And finally
```toml
#ruff.2.toml
[lint]
select = []
ignore = []
```

And command: `ruff check test.py`.

**Result**

No warnings, nothing. As expected.

**Change situation**

Add a random line like `foo=[]` to `ruff.2.toml`. Or moving the `select` outside of the `[lint]` block.

**Result**

Errors on running the command, like unknown rules. This is great, so it can find the file listed in `extend` and evaluates it properly.

**Change situation**

```toml
#ruff.toml
extend  = "./ruff.2.toml"
[lint]
select = ["ANN"]
ignore = []
```

```toml
#ruff.2.toml
[lint]
select = ["D"]
ignore = ["ANN001"]
```

**Result**

Expected: ANN001 to be supressed, ANN201 to be raised, D103 to be raised.

Actual: ANN001 is raised, ANN 201 is raised.

This is equivalent to only `ruff.toml` being used, in other words, `ruff.2.toml` is completely ignored, even though it is evaluated for correct syntax.

**Comment by charliermarsh** [comment]
If the `pyproject.toml` that contains an `extend` defines its own `select`, it effectively resets the selection chain. In your situation, you want `ruff.toml` to use `extend-select = ["ANN"]` instead of `select = ["ANN"]`.

**Comment by rogier-stegeman** [comment]
My `pyproject.toml` doesn't specify any ruff configuration, I assume you meant `ruff.toml`, and to pu tthe `extend-select` in my `ruff.2.toml`, the file which is extending.

First off, how would this work with `ignore`? The docs tell me `extend-ignore` is deprecated.

Second, my issue is not specifically with the `select` options not merging, the entire file found and validated by `extend`, is not actually used. Rules like `line-length` and 

```toml
[lint.pyupgrade]
keep-runtime-typing = true
```
Are also ignored in my extended file (`ruff.2.toml`). This while the file is correctly found by the `extend` rule because any syntax errors in the `ruff.2.toml` cause an error when running any ruff command.
