### ISSUE TITLE
Option to allow `extend`ing a file available at an HTTPS URL

### ISSUE THREAD

**Issue by lengau** [astral-sh/ruff#13245]
The current `extend` configuration is great for large monorepos where we want to extend configuration from a higher level, but for teams that have multiple separate repos, but still want a unified base configuration, it would be useful to allow `extend` to extend a remote file (with that file being cached for offline use).

For example:

```toml
[tool.ruff]
extend = "https://raw.githubusercontent.com/canonical/starbase/v1/pyproject.toml"
```

This is similar to [Mend Renovate's `extends`](https://docs.renovatebot.com/configuration-options/#extends) but without the complexity of converting repository descriptions to URLs.
