### ISSUE TITLE
Pattern in `lint.isort.sections` overrides detected `first-party` 

### ISSUE THREAD

**Issue by sscherfke** [astral-sh/ruff#13309]
Ruff version: 0.6.3
Rule: `I001` `unsorted-imports`

----

All our internal packages have a common prefix (e.g., `spam_`).

We want to declare these internal packages as "second party" and create a corresponding import section between third-party and first party sections.

The minimal configuration for this is

```toml
[lint]
select = ["I"]

[lint.isort]
lines-after-imports = 2
section-order = ["future", "standard-library", "third-party", "second-party", "first-party", "local-folder"]

[lint.isort.sections]
second-party = ["spam_*"]
```

Or as cmd line args:  `ruff check --fix --isolated --select I --config 'lint.isort.section-order = ["future", "standard-library", "third-party", "second-party", "first-party", "local-folder"]' --config 'lint.isort.sections.second-party = ["spam_*"]'`

Expected result:

```python
import os
import sys

import attrs
import rich

import spam_lib_a
import spam_lib_b

import spam_current_project
```

Current result:

```python
import os
import sys

import attrs
import rich

import spam_current_project
import spam_lib_a
import spam_lib_b
```

It looks like the pattern for the `second-party` section overides the packages collected from the local folder.
The issue seems related to https://github.com/astral-sh/ruff/issues/11542

**Comment by MichaReiser** [comment]
@charliermarsh, do you know how to configure the desired behavior?

**Comment by charliermarsh** [comment]
This behavior looks correct to me? Explicitly-defined sections do take precedence over the default sections. `spam_current_project` matches `spam_*`, so it will always be classified as `second-party`.

I think you could perhaps do something like this:

```toml
[lint]
select = ["I"]

[lint.isort]
lines-after-imports = 2
section-order = ["future", "standard-library", "third-party", "second-party", "current-project", "local-folder"]

[lint.isort.sections]
current-project = ["spam_current_project"]
second-party = ["spam_*"]
```
