### ISSUE TITLE
duplicate return statements after pre-commit run

### ISSUE THREAD

**Issue by mpurusottamc** [astral-sh/ruff#13310]
Some times, after running pre-commit, i notice duplicate return statements in the last function of the file.

Ex:
```python
return api_response

return api_response
```

See screenshot here for reference.
![Screenshot 2024-09-10 at 9 14 35 AM](https://github.com/user-attachments/assets/827de607-4e86-4977-b810-9ae7f62e57f8)

Here's the pre-commit command I run:
```shell
pre-commit run --all-files --show-diff-on-failure
```

Here's how my `.pre-commit-config.yaml` looks like:
```yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.4
    hooks:
      - id: ruff
        args:
          [--fix, --exit-non-zero-on-fix, "--line-length=120", "--ignore=E501"]
      - id: ruff-format
```

Sometimes, i have noticed, there are > 5 return statements. Depending on how many times pre-commit was run. I have not been able to reproduce repeatedly. Will share if I am able to find the steps.

Ruff Version: `ruff 0.1.9`
