### ISSUE TITLE
Allow character ranges in `allowed-confusables` for RUF001, RUF002, & RUF003

### ISSUE THREAD

**Issue by namurphy** [astral-sh/ruff#13330]
Rules [RUF001](https://docs.astral.sh/ruff/rules/ambiguous-unicode-character-string/), [RUF002](https://docs.astral.sh/ruff/rules/ambiguous-unicode-character-docstring/), and [RUF003](https://docs.astral.sh/ruff/rules/ambiguous-unicode-character-comment/) help flag potentially ambiguous Unicode characters. While the configuration variable `allowed-confusables` can be used to specify allowed Unicode characters, it can become cumbersome to define `allowed-confusables` for projects whose docstrings use a lot of mathematical notation, or projects that are written in languages that use (for example) the Cyrillic alphabet.  

It would be quite convenient if `allowed-confusables` could contain character ranges. Some possible use cases are:

```toml
allowed-confusables = ["α-ω"]  # lower case Greek letters for use in equations
allowed-confusables = ["∀-⋿"]  # Mathematical operators Unicode block
allowed-confusables = ["Ѐ-ӿ"]  # Cyrillic alphabet
```

Allowing character ranges would make it easier to configure exceptions to these rules.  It'd also be less likely that we'd forget to include certain Unicode characters.  

Many thanks!
