### ISSUE TITLE
I want a universal configuration that most people are used to.

### ISSUE THREAD

**Issue by lqllife** [astral-sh/ruff#13433]
I just started using ruff and never used black before, so I want to ask if there are any standard, commonly used and easy-to-use rules.
I searched for a long time in the issue but couldn't find it, so I'm asking.
Please give me some ready-made rules, preferably with some brief descriptions, thank you.
Here are my pyproject.toml configuration.

```toml
[project]
name = "flask_test"
version = "0.1.0"
description = "falsk test"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask~=2.3.2",
    ...
]

# 开发环境依赖
[tool.uv]
dev-dependencies = [
    "pytest >=8.1.1,<9",
    "ruff>=0.6.6",
]

# ruff 自动化校验
[tool.ruff]
target-version = "py310"
exclude = [".venv", "*.pyi"]
src = ["app", "tests"]
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = ["E", "F", "UP", "W"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
```
