### ISSUE TITLE
new rule - detecting string enumerations that look like string concatenations

### ISSUE THREAD

**Issue by spaceby** [astral-sh/ruff#13534]
```python
a = ('Hello ',
     + 'world')
```
This looks like an explicit string concatenation, but it's actually an enumeration of strings.
I wish ruff would detect this

It seems it should work when there is the following configuration

```toml
[tool.ruff.lint.flake8-implicit-str-concat]
allow-multiline = false
```
