### ISSUE TITLE
False positive for TCH002 when type used in a method

### ISSUE THREAD

**Issue by last-partizan** [astral-sh/ruff#13926]
I'm using DRF and drf-spectacular, and it uses runtime type introspection for some cases (like `serializers.SerializerMethodField()`. And i have no way to tell `ruff` to not move those types into TYPE_CHECKING block.

I tried `runtime-evaluated-base-classes`, but looks like it only works for class fields, not class methods.

```
> ruff --version
ruff 0.7.1
```

```toml
[tool.ruff]
target-version = "py39"

[tool.ruff.lint]
select = ["TCH"]

[tool.ruff.lint.flake8-type-checking]
runtime-evaluated-base-classes = [
	"rest_framework.serializers.Serializer",
	"rest_framework.serializers.ModelSerializer",
]
```

```py
from __future__ import annotations

from rest_framework import serializers

from app.models import Book


class BookSerializer(serializers.Serializer):
    name = serializers.SerializerMethodField()

    def get_name(self, instance: Book) -> str:
        return instance.name
```

```sh
> ruff check --select TCH project/serializers.py
project/serializers.py:5:24: TCH002 Move third-party import `app.models.Book` into a type-checking block
  |
3 | from rest_framework import serializers
4 |
5 | from app.models import Book
  |                        ^^^^ TCH002
  |
  = help: Move into type-checking block
```

Workaround for this is probably using `runtime-evaluated-base-classes` and adding `instance: MyClass` for affected serializers. But would be nice to have proper solution.
