### ISSUE TITLE
Adding new class of static analysis rules using LLMs

### ISSUE THREAD

**Issue by bbkgh** [astral-sh/ruff#14085]
Hi, I would like to suggest adding a new class of rules to Ruff that utilizes Local/Remote LLM APIs for running rules over code files. I believe this can greatly improve code quality and result in fewer bugs. Additionally, writing rules in plain text is more convenient. For example, we could have a llm_rules.yaml file to project containing something like this:

```yaml
type: ollama/qwen2.5
endpoint: http://localhost:11434
rules:
  - "There must not be any usage of datetime.now(); use timezone.now() from django.utils instead"
  - "There must not be any Typos in comments"
  - "Always use MyCustomObject for calling ServiceX"
```
