### ISSUE TITLE
Feature Request: Allow re-including directories that were excluded in parent config

### ISSUE THREAD

**Issue by nuncaeslupus** [astral-sh/ruff#14226]
Searched keywords: "include", "exclude", "extend-include", "extend-exclude"
Ruff version: 0.3.0

## Use Case
When using `extend` to inherit from a parent `pyproject.toml`, there's currently no way to selectively re-include directories that were excluded using `extend-exclude` in the parent config. This is particularly problematic when:

1. Working with team configurations where the root `pyproject.toml` is tracked in version control and excludes certain directories
2. Developers want to apply Ruff to those excluded directories in their local development environment without modifying the team's config

## Current Workarounds
Currently, the only workarounds are:
- Create a completely separate config without extending the parent (requires manual syncing of settings)
- Write a script to sync configurations while removing exclusions
- Modify team's config to use more specific exclusion patterns

Neither solution is ideal as they either require extra maintenance or modify team-wide settings.

## Proposed Solution
Add the ability to re-include previously excluded directories, either through:

1. A new `include-dirs` option that would take precedence over `extend-exclude`:
```toml
[tool.ruff]
extend = "../pyproject.toml"  # Parent has extend-exclude = ["tmp"]
include-dirs = ["tmp"]  # Override the exclusion for this directory
```

2. Or allow `extend-exclude = []` to clear inherited exclusions, then redefine them as needed:

```toml
[tool.ruff]
extend = "../pyproject.toml"
extend-exclude = []  # Clear inherited exclusions
```
This would provide more flexibility for local development workflows while maintaining team-wide configurations.
