### ISSUE TITLE
Imports split using a backlash are reverted by `ruff format`

### ISSUE THREAD

**Issue by PatrickJordanNutanix** [astral-sh/ruff#14294]
We have an import statement that exceeds our line length limit of 79 characters. The path to the class being imported fits within the line length limit but the `import` exceeds it. For example:

```python
from our_internal_sdk_package.namespace_1.overly_verbose_long_module_name import ClassName
                                                                                ^ # line length limit here
```

We unfortunately do not have the ability to shorten the path as it's from an internal SDK that is autogenerated from an OpenAPI specification and have already released it, so cannot make breaking changes without upsetting a lot of people.

Naturally, we would format this like:

```python
from our_internal_sdk_package.namespace_1.overly verbose_long_module_name \
  import ClassName
```

However, when we run the following, `ruff` isn't happy:

```
> ruff format --diff --quiet

-from our_internal_sdk_package.namespace_1.overly_verbose_long_module_name \
-  import ClassName
+from our_internal_sdk_package.namespace_1.overly_verbose_long_module_name import (
+  ClassName,
+)
```

Running the formatter causes it to reformat this import statement, then throw an `E501` linting error.

Is there a setting we need to change to have it respect the backslash splitting (without using `# fmt: off|on` or `# noqa: E501` pragma comments)?

### Supporting Information

Version:

```shell
> ruff --version                                                                        
ruff 0.6.8
```

Contents of `ruff.toml`:

```toml
indent-width = 2
line-length = 79
exclude = [{internal_packages}]

[format]
quote-style = "double"
indent-style = "space"

[lint]
select = ["I"]

[lint.isort]
known-first-party = [{internal_packages}]
```
