### ISSUE TITLE
[Linter panic] when fixing W391 in Jupyter notebook

### ISSUE THREAD

**Issue by beskep** [astral-sh/ruff#14445]
- command: `ruff check .\src\test.ipynb --fix --diff`
(No panic when `--isolated` included)

- ruff version: 0.7.4

- pyproject.toml
```toml
[project]
requires-python = ">=3.13"
dependencies = ["ruff>=0.7.4"]

[tool.ruff]
preview = true

[tool.ruff.lint]
select = ["W"]
```

- ipynb file: [test.ipynb.zip](https://github.com/user-attachments/files/17807695/test.ipynb.zip)
