### ISSUE TITLE
dotted key `mypy.plugins` attempted to extend non-table type (array)

### ISSUE THREAD

**Issue by skhaz** [astral-sh/ruff#14528]
I have this `pyproject.toml`

```toml
[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = ["F", "I"]

[tool.ruff.lint.isort]
force-single-line = true

[mypy]
plugins = ["mypy_django_plugin.main"]

[mypy.plugins.django-stubs]
django_settings_module = "gatekeeper.settings"
```

Which works fine.

When I run

```shell
ruff format . && ruff check --fix .
```

I get the following error

```
ruff failed
  Cause: Failed to parse /opt/workspace/company/project/pyproject.toml
  Cause: TOML parse error at line 18, column 1
   |
18 | [mypy.plugins.django-stubs]
   | ^
invalid table header
dotted key `mypy.plugins` attempted to extend non-table type (array)
```
