### ISSUE TITLE
Allow (formatter?) config to never introduce implicit concatted strings or just accept that a check run will complain about it

### ISSUE THREAD

**Issue by jankatins** [astral-sh/ruff#14638]
I think implicitly concat'ed strings are pure evil since a time where I had to debug an accidentally added comma in a place where `+` would have been proper, which made a single string a tuple of two strings. I would like ruff to allow this and not complain about this, but currently it does complain and IMO it complains for the wrong reasons and with the wrong solution: 

I don't want it to stop complaining about implicitly concat'ed strings, but stop the formatter from introducing them by using a '+' between multiline strings. Or if it introduces implicitly concat'ed strings (because + would be a black vialoation), just complain (when it happens), so I'm forced to fix it by hand (which I would be fine with). But having the scary warning in all runs makes me and especially unwary users scared into disabling that rule. :-(

Inspired by https://github.com/astral-sh/ruff/issues/13031#issuecomment-2302402183, I would have expected that

```toml
[tool.ruff.lint]
extend-select = ["ISC"]
ignore=["ISC003"] # Don't complain about explicitly concat'ed strings
unfixable = ["ISC001"] # don't fix one line implicitly concat'ed strings, but just complain and make the user fix it

[tool.ruff.lint.flake8-implicit-str-concat]
allow-multiline = false
```

would work, but ruff still complains, that this is incompatible with the formatter:

```
 The following rule may cause conflicts when used with the formatter: `ISC001`. To avoid unexpected behavior, we recommend disabling this rule, either by removing it from the `select` or `extend-select` configuration, or adding it to the `ignore` configuration.
```
