### ISSUE TITLE
RUF200 explanation is misleading/wrong

### ISSUE THREAD

**Issue by knirch** [astral-sh/ruff#14975]
> ## Example
> ```toml
> [project]
> name = "crab"
> version = "1.0.0"
> authors = ["Ferris the Crab <ferris@example.org>"]
> ```
> 
> Use instead:
> ```toml
> [project]
> name = "crab"
> version = "1.0.0"
> authors = [
>   { email = "ferris@example.org" },
>   { name = "Ferris the Crab"}
> ]
> ```

which I assume meant to say;

```toml
[project]
name = "crab"
version = "1.0.0"
authors = [
  { name = "Ferris the Crab", email = "ferris@example.org" }
]
```
otherwise how would this trio author a project? 
```toml
[project]
name = "llm-fueled-cringe"
authors = [
  { name = "Ferris the Crab", email = "ferris@example.org" }, 
  { name = "Cameron the Tortoise" },
  { email = "ed.peacock@example.org" }
]
```
