### ISSUE TITLE
Populate `[tool.ruff.lint.flake8-quotes.inline-quotes]` from `[tool.ruff.format.quote-style]`

### ISSUE THREAD

**Issue by sobolevn** [astral-sh/ruff#14990]
When configuring `flake8-quotes` together with the formatter, it seems strange to specify the type of quotes you use twice:

```toml
[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
```

I propose using `quote-style` from `[tool.ruff.format]` as a default value for `inline-quotes` from `[tool.ruff.lint.flake8-quotes]`.

If others agree, I can send a PR.
