### ISSUE TITLE
known-third-party not respected when the project root (local folder) contains a subfolder with the same name as a declared import

### ISSUE THREAD

**Issue by Dev-iL** [astral-sh/ruff#15098]
## Background
I have a project with the following structure:

```none
📂 my_project
┣━━ 📂 airflow    <- possibly an implicit namespace package, see note at the end
┃   ┗━━ 📂 dags
┃       ┣━━ 🐍 __init__.py
┃       ┣━━ 🐍 dag_1.py
┃       ┣━━ ...
┃       ┗━━ 🐍 dag_n.py
┣━━ 📂 src
┃   ┗━━ 📂 my_lib
┃       ┣━━ 🐍 __init__.py
┃       ┗━━ ...
┗━━ 📄 pyproject.toml
```

In my `pyproject.toml` I have the following sections related to import sorting:

```toml
[tool.ruff.lint.isort]
known-third-party = ["airflow"]
section-order = ["future", "standard-library", "third-party", "company-libs", "first-party", "local-folder"]

[tool.ruff.lint.isort.sections]
company-libs = ["my_other_lib"]
```

## Observed behavior
Whenever I have imports of the form
```python
from airflow import DAG  # This refers to the 3rd-party library; I never import from the top-level `airflow` folder

from my_other_lib import foo
```

Ruff issues an [I001](https://docs.astral.sh/ruff/rules/unsorted-imports/) and rearranges them to 
```python
from my_other_lib import foo

from airflow import DAG
```

## Expected behavior
The imports should remain unchanged, per the `pyproject.toml` configurations.

## Additional notes
- isort handles this as expected.
- Deleting `my_project/airflow/dags/__init__.py` stops this behavior from happening.
- I might have oversimplified the example for sharing. If the issue is unreproducible - I'll revise the post.
