### ISSUE TITLE
feature request: option for non newline sensitive output of call-expressions-with-a-single-multiline-string-argument

### ISSUE THREAD

**Issue by trim21** [astral-sh/ruff#15458]
We have a newline sensitive output for the case of https://docs.astral.sh/ruff/formatter/black/#call-expressions-with-a-single-multiline-string-argument

Is it possible to have a formatter option to remove the newline sensitivity?

(I have no option on which style is the best and what output it should yield, but I don't like the different format result caused by newline)

For example

```
# Input
call(
  """"
  A multiline
  string
  """
)

dedent(""""
    A multiline
    string
""")
```

with:

```toml
[tool.ruff.format]
call-expressions-with-a-single-multiline-string-argument = 'preserve'
```

we don't change the code, which is the current behavoir

and for

```toml
[tool.ruff.format]
call-expressions-with-a-single-multiline-string-argument = 'add-indent' # or call if black?
```

we yield same output with black:

```python
call(
    """
  A multiline
  string
  """
)

dedent(
    """
    A multiline
    string
"""
)
```

and for

```toml
[tool.ruff.format]
call-expressions-with-a-single-multiline-string-argument = 'hug' # or some other option name
```

we always yield

```python
call("""
  A multiline
  string
  """)

dedent("""
    A multiline
    string
""")
```
