### ISSUE TITLE
A006 builtin-lambda-argument-shadowing ignores exceptions

### ISSUE THREAD

**Issue by Zer0x00** [astral-sh/ruff#15467]
The [documentation](https://docs.astral.sh/ruff/rules/builtin-lambda-argument-shadowing/) describes, that setting an exception in pyproject.toml should exclude this module from being marked as a lint error.

However setting it like this:
```toml
[tool.ruff.lint.flake8-builtins]
builtins-ignorelist = ["secrets"]
```

doesn't seem to work for A006.
