### ISSUE TITLE
What is the list of rules that setting Google convention is equivalent to?

### ISSUE THREAD

**Issue by galenseilis** [astral-sh/ruff#16098]
### Description

The documentation says we can set to [Google's style](https://google.github.io/styleguide/pyguide.html) conventions. For example:

```toml
[tool.ruff.lint]
# Enable D400 on top of the Google convention.
extend-select = ["D400"]

[tool.ruff.lint.pydocstyle]
convention = "google"
```

I didn't see a list of the rules that setting `convention = "google"` is equivalent to. Is that list available somewhere?
