### ISSUE TITLE
Rename settings names to focus on user-friendliness rather than provenance

### ISSUE THREAD

**Issue by NeilGirdhar** [astral-sh/ruff#16313]
### Description

Please consider renaming settings to make their names as easy to read as possible.  I recognize that historically, the "flake8-bandit" plugin's rules are provided by Ruff.  But contemporary users may not have ever even used or configured flake8-bandit.

Consider settings like:
```toml
[tool.ruff.lint.flake8-errmsg]
max-string-length = 40

[tool.ruff.lint.flake8-bandit]
check-typed-exception = true
```
Would this be better?
```toml
[tool.ruff.lint.exceptions]  # These both have to do with exceptions, so why not group them?
max-string-length = 40
disallow-try-except = true  # Name is closer to meaning.
```

In general, is it really important to keep the "flake8", "pylint", "pyflakes" prefixes anywhere, or are they an anachronism?

Here's an hard to decipher option:
```toml
[tool.ruff.lint.flake8-gettext]
extend-function-names = ["ugettetxt"]
```
How about
```toml
[tool.ruff.lint.internationalization]  # or i18n or just gettext?
extend-function-names = ["ugettetxt"]
```
