### ISSUE TITLE
[Formatter panic]

### ISSUE THREAD

**Issue by xodiumx** [astral-sh/ruff#16476]
Hello, I am getting an error in the formatter
____
> pyproject.toml:

```
[tool.ruff]
line-length = 120
target-version = "py312"
```
____
> .pre-commit-config.yaml

```yaml
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
```
____
> stacktrace

```
panicked at
 crates/ruff_source_file/src/line_index.rs:117:28:
byte index 472 is not a char boundary; it is inside 'а' (bytes 471..473) of `import pandas as pd
import numpy as np

from sklearn.datasets import make_regression, fetch_california_housing
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
RANDOM_STATE = 123
TRAIN_SIZE = 0.75
np.random.RandomSt`[...]
Backtrace:    0: __mh_execute_header
   1: __mh_execute_header
   2: __mh_execute_header
   3: __mh_execute_header
   4: __mh_execute_header
   5: __mh_execute_header
   6: __mh_execute_header
   7: __mh_execute_header
   8: __mh_execute_header
   9: __mh_execute_header
  10: __mh_execute_header
  11: __mh_execute_header
  12: __mh_execute_header
  13: __mh_execute_header
  14: __mh_execute_header
  15: __mh_execute_header
  16: __mh_execute_header
  17: __mh_execute_header
  18: __mh_execute_header
  19: __mh_execute_header
  20: __mh_execute_header
  21: __mh_execute_header
  22: __mh_execute_header
  23: __pthread_deallocate
```
