### ISSUE TITLE
Allow custom exceptions to N806, N815, N816

### ISSUE THREAD

**Issue by janosh** [astral-sh/ruff#16551]
### Summary

in the physical sciences, certain variables have widely used notations that conflict with Python's snake case convention. e.g.

```py
# kT: initial temperature in metal units (K)
kT = 80 * Units.temperature  # noqa: N816
```

would be great if you could whitelist certain non-snake case variables in `pyproject.toml`

```toml
[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN002",  # Checks that *args arguments have type annotations.
    "ANN003",  # Checks that **kwargs arguments have type annotations.
    # ...
]
pydocstyle.convention = "google"
isort.split-on-trailing-comma = false
mixed-case-variable-in-global-scope-whitelist = ["kT"]  # new config option proposal
```
