### ISSUE TITLE
[IMPROVEMENT] Make `--select` other CLI short hands more lenient with whitespace

### ISSUE THREAD

**Issue by lenormf** [astral-sh/ruff#16755]
### Summary

Hi!

I would like the `--select`, `--ignore` and other short hand options passed to `ruff check` to be more lenient with whitespace characters, between rule codes.

I found myself writing a PreCommit configuration, like so:

```yaml
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.0
    hooks:
       - id: ruff
         args:
           - --fix
           - |-
               --select=
               A,
               B
```

This lead to the hook invoking `ruff check --fix --select=' A, B' <file>`, with the result below:

```
error: invalid value ' A' for '--select <RULE_CODE>'
```

I couldn’t find any syntax in YAML that would allow joining a string within a block sequence item _without_ space characters.

Therefore, I believe it would be a convenient improvement to allow whitespace in the comma-separated list of rules that `ruff check --<shorthand>` accepts.

Thanks!

### Version

0.11.0

**Comment by ntBre** [comment]
This may not be a perfect workaround, but it looks like ruff allows multiple `--select` flags, so you could instead do something like

```yaml
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.0
    hooks:
       - id: ruff
         args:
           - --fix
           - |-
               --select=A
               --select=B
```

(If my limited YAML syntax understanding is sufficient here)

Another option would be putting these in a `ruff.toml` or other config file, but maybe that doesn't work well with pre-commit.

We could still considering trimming spaces, but these might help in the meantime.
