### ISSUE TITLE
Add support for flake8-datetime-import

### ISSUE THREAD

**Issue by DmytroLitvinov** [astral-sh/ruff#17218]
### Summary

HI there,

I like the idea of flake8 plugin called [flake8-datetime-import](https://github.com/marcgibbons/flake8-datetime-import). It is always a mess kinda in projects how its imported. The motivation and other notable links mentioned at README of repository.

One of the link is mentioned to [Adam Johnson post](https://adamj.eu/tech/2019/09/12/how-i-import-pythons-datetime-module/ ) - well-known Python/Django guy who do a lot for community and he write and create a lot of useful stuff in his [blog](https://adamj.eu/) and at [GitHub](https://github.com/adamchainz)

**Comment by loRes228** [comment]
I don't think it makes sense, because there's - https://docs.astral.sh/ruff/settings/#lint_flake8-import-conventions_aliases

```toml
[tool.ruff.lint.flake8-import-conventions.extend-aliases]
"datetime" = "dt"
"time" = "tm"
```
