### ISSUE TITLE
Support for `per-file-select` to simplify incremental rule adoption in monorepos

### ISSUE THREAD

**Issue by mgaitan** [astral-sh/ruff#17391]
We're currently running into a limitation related to `select` granularity. In our setup, we want to **enable all `B` (flake8-bugbear) rules only for a specific subdirectory**, e.g., `infrastructure/**/*.py`, while **keeping a small, curated subset of `B` rules for the rest of the codebase**.

Since `per-file-select` is not supported, the only way to do this today is to add `"B"` to the global `select` list, and then **manually disable every unwanted `B` rule for all other paths using `per-file-ignores`**.

```toml
[tool.ruff.lint]
select = ["E", "F", "B"]

[tool.ruff.lint.per-file-ignores]
"!infrastructure/**/*.py" = [
  "B011", "B012", "B013", "B014", "B015", "B017", "B019", "B020", "B024", "B028", ...
]
```

This approach has two major downsides:

1. It's hard to maintain and scales poorly with monorepos.
2. **If a new `B` rule is added in a Ruff update**, it will immediately start triggering errors in all non-`infrastructure` code — unless we explicitly add it to the `per-file-ignores`, which makes upgrades error-prone.

Instead, we'd love to see support for something like:

```toml
[tool.ruff.lint]
select = ["E", "F", "B006", "B007"]

[tool.ruff.lint.per-file-select]
"infrastructure/**/*.py" = ["B"]
```

This would allow teams to **adopt rules incrementally in targeted parts of the codebase**, without negatively affecting the rest of the project. It would significantly improve maintainability and unlock cleaner linting strategies in larger codebases.

This idea has already come up in a couple of discussions by @carljm:

- https://github.com/astral-sh/ruff/issues/11042#issuecomment-2067022376 
- https://github.com/astral-sh/ruff/pull/10863#discussion_r1561770000

PS: Thanks for your great work!
