### ISSUE TITLE
Glob pattern in definition of custom section is not working

### ISSUE THREAD

**Issue by FateXRebirth** [astral-sh/ruff#18085]
### Summary

According to https://docs.astral.sh/ruff/settings/#lint_isort_sections this doc, We are able to create a custom section and rearrange the order of sections, and I notice that you are using https://docs.rs/globset/latest/globset/ to handle that.

So I wrote the following code:
```toml
[lint.isort.sections]
"private" = ["[.]*"]

[lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder", "private"]
```

What I want to achieve is just to place the package start with `.` or `..` to be placed in the end of all sections
Like this:
```python
import os
...
import pdfkit
...
from services.user_service import get_user
...
from .search_export import search_service
from ..search_export.service import get_result
```

But it is not working, I've tried the glob pattern in my rust project, it works as I expect

Is there anything I miss or I do wrong?

### Version

ruff 0.11.7
