### ISSUE TITLE
Clarify documentation for `lint.extend-ignore` and `lint.extend-select` settings

### ISSUE THREAD

**Issue by Tedpac** [astral-sh/ruff#18884]
These settings and their usefulness can be (and have been, from what I've seen in multiple issues) easily misunderstood.

For example, the following configurations are equivalent:

```toml
[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint]
# Configuration 1
select = ["ALL"] 
extend-select = ["D213"]
extend-ignore = ["D212"]

# Configuration 2
select = ["ALL", "D213"] 
ignore = ["D212"]
```

On the other hand, it seems that `lint.extend-ignore` [was mistakenly deprecated](https://github.com/astral-sh/ruff/pull/12007#issuecomment-2186270791), and it is confusing to see that `lint.extend-ignore` is deprecated while `lint.extend-select` is not.

The documentation should include clear use cases for when these settings are useful. From what I understand, these settings are primarily valuable when:
- Using the top-level `extend` setting to inherit from base configurations.
- Adding rules on top of the default rule set without completely overriding it.
