### ISSUE TITLE
Simplify rule selection settings

### ISSUE THREAD

**Issue by Tedpac** [astral-sh/ruff#19007]
I've been thinking more deeply about an issue I raised a few days ago (#18884), and IMO, the rule selection settings can be simplified considerably.

## Proposal

1. Deprecate the `lint.select`/`lint.ignore` and `lint.extend-select`/`lint.extend-ignore` settings.
2. Implement the following settings:

- `lint.rules`
- `lint.extend-rules`

3. Apply the same logic as `lint.select`/`lint.extend-select` to these settings, adding logic to ignore rules that start with `!`. For example, `!D213`. An alternative symbol could be `-` (e.g. `-D213`).

## Why is this better?

1. Fewer settings (more simplicity).
2. Greater maintainability, since everything related to rule selection will be in a single setting. For example:

```toml
[tool.ruff.lint]
rules = [
  "ALL",
  "!D212", "D213"  # Start docstrings on the second line.
]

[tool.ruff.lint.pydocstyle]
convention = "google"
```

> [!NOTE]
>  On a single line (or block, if you prefer), you can select and ignore rules, as well as comment on what you want to achieve. This level of documentation and maintainability cannot be achieved with separate settings, as is currently the case.

3. Better naming of settings:

- `rules` and `extend-rules` are **explicit**.
- `rules` and `extend-rules` are **plural**, as arrays should be.
