### ISSUE TITLE
(🎁) Ability to specify default files in the config

### ISSUE THREAD

**Issue by KotlinIsland** [astral-sh/ruff#3970]
I want to be able to specify the default files within the configuration file so that I don't need to duplicate this config in different places.

```toml
[tool.ruff]
files = ["src", "scripts"]
```

Then it is possible to invoke ruff without passing any paths:
```
👉 ruff
yada yada yada
```
