### ISSUE TITLE
`resources` imported but unused

### ISSUE THREAD

**Issue by IamRezaMousavi** [astral-sh/ruff#4250]
`resources.py` must imported to use `Qt resources` in project
resources file will generated by:
`pyrcc5 resources.qrc -o "./resources.py"`

how can I tell ruff to ignore resources import error??

ruff output:
`window.py:22:26: F401 [*] resources imported but unused`

pyproject.toml:
```toml
[tool.ruff]
line-length = 100

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"resources.py" = ["E501"]
"colorbox.py" = ["E722"]
"test.py" = ["E402", "F401"]
```

ruff version:
`ruff 0.0.264`
