### ISSUE TITLE
providing settings for rules which are not generated should produce a warning

### ISSUE THREAD

**Issue by joaompinto** [astral-sh/ruff#4266]
```toml
# pyproject.toml
[tool.ruff.mccabe]
max-complexity = 1

[tool.flake8]
max-complexity = 1
```` 

```python
# test.py
def some_function():
    if 0 > 1:
        print("1")
    else:
        print("2")
```
```sh
pip install flake8 Flake8-pyproject ruff

$ ruff test.py
`` 
$ flake8 test.py
test.py:5:1: C901 'some_function' is too complex (2)

$ ruff test.py # No output produced

$ ruff --version
ruff 0.0.265
