### ISSUE TITLE
Conviguation via Cargo.toml (`[package.metadata.ruff]`)

### ISSUE THREAD

**Issue by tgross35** [astral-sh/ruff#4970]
Just a simple request - would it be possible to check `Cargo.toml` for rust configuration? This would be really cool for Rust projects that have a couple python scripts.

The [metadata table](https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table) can hold anything, so I'm just imagining something like this:

```toml
[package.metadata.ruff]
select = ["E", "F"]
ignore = []
# ... standard ruff config
```
