### ISSUE TITLE
new rule - ban all usages of `NoReturn` in favor of `Never`

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/ruff#5241]
discussed in https://github.com/astral-sh/ruff/issues/5111#issuecomment-1593892209, which was closed:

> imo having two separate types that do the exact same thing is just confusing and misleading. i've seen people misinterpret `NoReturn` to mean that the function returns `None`. having a separate `Never` type while not treating the old one as deprecated just makes that misinterpretation more likely. i feel like the name `NoReturn` was only picked because nobody considered the fact that there are other use cases for it, which is why i think it should be avoided altogether.
> 
> but i guess it comes down to personal preference, so perhaps a new rule could be created to ban all usages of `NoReturn`?

**Comment by DetachHead** [comment]
workaround:
```toml
[tool.ruff]
extend-select = ["UP035","TID25"]

[tool.ruff.flake8-tidy-imports.banned-api]
"typing.NoReturn".msg = "use `typing.Never` instead"
```
