### ISSUE TITLE
Infer Python target version from Poetry dependencies

### ISSUE THREAD

**Issue by MicaelJarniac** [astral-sh/ruff#5448]
Ruff is able to infer `tool.ruff.target-version` from `project.requires-python`, but not from Poetry's `tool.poetry.dependencies.python`.

Poetry is a rather large project, with [![Poetry stars](https://img.shields.io/github/stars/python-poetry/poetry?style=flat-square)](https://github.com/python-poetry/poetry) on GitHub, which is currently more than Ruff itself, at [![Ruff stars](https://img.shields.io/github/stars/astral-sh/ruff?style=flat-square)](https://github.com/astral-sh/ruff), so I'd say supporting it would be very nice and help a lot of people.

- https://github.com/python-poetry/poetry
- https://beta.ruff.rs/docs/settings/#target-version
- https://python-poetry.org/docs/pyproject/#dependencies-and-dependency-groups

`pyproject.toml` using Poetry:
```toml
[tool.poetry]
name = "my-project"
version = "0.0.0"
description = "My project."
authors = ["Author <author@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.ruff]
target-version = "py38"  # This shouldn't be, necessary
```
