### ISSUE TITLE
Get the first item from an iterable

### ISSUE THREAD

**Issue by Hoxbro** [astral-sh/ruff#5503]
Sometimes I need to get the first item of an iterable like a `dict_keys()` object. A natural way to do this is to do it with `list(...)[0]`, though it can be much faster to do it with `next(iter(...))`. 

I have tried to see if a rule already describes this, but I could not find it.

Some examples: 

``` yaml
Examples with list(...)[0] with length of 1000
Dictionary:	1000 loops, best of 5: 4.35 usec per loop
List:		1000 loops, best of 5: 1 usec per loop
Range:		1000 loops, best of 5: 5.6 usec per loop

Examples with next(iter(...)) with length of 1000
Dictionary:	1000 loops, best of 5: 34.3 nsec per loop
List:		1000 loops, best of 5: 33.1 nsec per loop
Range:		1000 loops, best of 5: 27.7 nsec per loop

```

<details> 

<summary> Code </summary>

``` bash


N=1000
echo "Examples with list(...)[0] with length of $N"
echo -n -e "Dictionary:\t"
python -m timeit --s="a = {i: i for i in range($N)}" --n 1000 "list(a)[0]"
echo -n -e "List:\t\t"
python -m timeit --s="a = [i for i in range($N)]" --n 1000 "list(a)[0]"
echo -n -e "Range:\t\t"
python -m timeit --s="a = range($N)" --n 1000 "list(a)[0]"

echo -e "\nExamples with next(iter(...)) with length of $N"
echo -n -e "Dictionary:\t"
python -m timeit --s="a = {i: i for i in range($N)}" --n 1000 "next(iter(a))"
echo -n -e "List:\t\t"
python -m timeit --s="a = [i for i in range($N)]" --n 1000 "next(iter(a))"
echo -n -e "Range:\t\t"
python -m timeit --s="a = range($N)" --n 1000 "next(iter(a))"

```
</details>
