### ISSUE TITLE
False Positive `DTZ005`: When using `datetime.datetime.now().astimezone()`

### ISSUE THREAD

**Issue by LawrenceJGD** [astral-sh/ruff#5516]
The DTZ005 rule of flake8-datetimez throws an error when using the `datetime.datetime.now()` class method without the `tz` argument in `now()` or when the argument is `None`, it does this to avoid problems with `datetime.datetime` objects without a timezone, but there is a way to get the local time and date using `datetime. datetime.now().astimezone()`, when astimezone() detects that the object does not have a timezone then it assigns the local one, but still flake8-datetimez detects this as an error, so it would be better to fix it, since in the end the object ends up having a timezone.

This is referenced by pjknkda/flake8-datetimez#9 and #1249.

The command I use is `ruff check test.py` and the example source code is this:

```python3
import datetime

datetime.datetime.now().astimezone()
```

I'm using ruff 0.0.269 and my `pyproject.toml`:

```toml
[tool.ruff]
select = [
    "W", "C90", "I", "N", "D", "UP", "YTT", "ANN", "S", "BLE", "FBT", "B", "A",
    "COM", "C4", "DTZ", "ICN", "PIE", "RSE", "RET", "SLF", "SIM", "TCH", "RUF",
    "INT", "ARG", "TD", "EM", "PLC", "PLE", "PLR", "PLW", "TRY", "FLY", "E",
    "F"
]
line-length = 88
target-version = "py38"
ignore = ["COM812"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311"]
```
