### ISSUE TITLE
Ruff is not able to fix errors on autofix when done through precommit hook

### ISSUE THREAD

**Issue by sahajvss** [astral-sh/ruff#5647]
pre-commit config:
```
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.277
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
```

I'm still getting E501 errors which should ideally get fixed as autofix is enabled. Not sure if i'm missing something or if it's an issue.
