### ISSUE TITLE
Getting "error: Failed to converge after 100 iterations", rule I002, required-imports with syntax from ... import ... as ...

### ISSUE THREAD

**Issue by guillaumeLepape** [astral-sh/ruff#5784]
Hello,

When I'm trying to autofix a I002 error with `required-imports = ["from __future__ import annotations as _annotations"]`, I'm getting an error which I believe is a bug.

To reproduce the isssue, I create the following files

### pyproject.toml
```toml
[tool.ruff]
select = ["I"]
fix = true

[tool.ruff.isort]
required-imports = ["from __future__ import annotations as _annotations"]

```
### main.py
```
x = 1

print(x)
```

If I run `ruff main.py` for the first time, I got 
```log

error: Failed to converge after 100 iterations.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BInfinite%20loop%5D

...quoting the contents of `main.py`, the rule codes I002, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

main.py:1:1: I002 Missing required import: `from __future__ import annotations`
Found 101 errors (100 fixed, 1 remaining).
```
and ruff adds `from __future__ import annotations` at the beginning of the file. If I reruns it, I got the same error and no changes to the python file.
