### ISSUE TITLE
isort clash with ruff I001 when module has digit

### ISSUE THREAD

**Issue by mmarras** [astral-sh/ruff#6043]
isort sorts imports in a way that induces ruff to flag `I001`, aka ruff and isort want to sort the imports in different ways (I suspect when module has a number in name). 

after running isort
```python
from basic.views import datamore_login_required
from geln_main import config as config_main
from geln_olga2 import config
from geln_olga2.models import Data
from geln_olga.pytools import olga
from geln_olga.views import get_histogram_data, validate_parse_sp2files
from global_log_usage.views import create_hit
```

then 
```sh
geln_olga2/views.py:1:1: I001 [*] Import block is un-sorted or un-formatted
Found 1 error.
[*] 1 potentially fixable with the --fix option.
```

after running ruff auto-correct (which I only apply manually to see the difference)
```python
from basic.views import datamore_login_required
from geln_main import config as config_main
from geln_olga.pytools import olga
from geln_olga.views import get_histogram_data, validate_parse_sp2files
from geln_olga2 import config
from geln_olga2.models import Data
from global_log_usage.views import create_hit
```

Relevant settings are: 

.pre-commit-config.yaml
```yaml
- repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
- repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.280"
    hooks:
      - id: ruff
```
