### ISSUE TITLE
[Feature] more of `isort`

### ISSUE THREAD

**Issue by joe733** [astral-sh/ruff#6190]
I'd like to aggregate feature request related specifically to `isort` here:

- [ ] https://github.com/astral-sh/ruff/issues/3759
- [ ] https://github.com/astral-sh/ruff/issues/3206
- [ ] https://github.com/astral-sh/ruff/issues/3119
- [ ] https://github.com/astral-sh/ruff/issues/3115
- [ ] https://github.com/astral-sh/ruff/issues/2601
- [ ] https://github.com/astral-sh/ruff/issues/2600
- [ ] https://github.com/astral-sh/ruff/issues/1567
- [ ] https://github.com/astral-sh/ruff/issues/1332

Feel free to add yours below if I missed any.

**Comment by mjpieters** [comment]
Is there a usecase for implementing [isort's presets](https://pycqa.github.io/isort/docs/configuration/profiles.html)? E.g. `preset = black` is short-hand for:

```toml
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
split_on_trailing_comma = true
```

Note that most of these settings are not available in Ruff (yet); the only exception being the last two options.
