### ISSUE TITLE
allow specifying a different `exclude` for each rule category

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/ruff#6225]
in my project, i don't want the pydocstyle `D` errors to appear in files matching a certain pattern (eg. so that internal modules do not require documentation).

using pydocstyle, that can be accomplished like this:
```toml
[tool.pydocstyle]
match = '(?!_?test_).*\.py'
```
however there seems to be no way to do this in ruff, without also disabling all other categories using the `exclude` option.

perhaps something like:
```toml
[tool.ruff]
exclude = ['*.pyi'] # global excludes

[tool.ruff.pydocstyle]
exclude = ['test_*.py', '_*.py'] # exclude option for specific tools (in addition to the global exclude patterns)
```
