### ISSUE TITLE
`function-uses-loop-variable` (`B023`) - option to define functions where lambda is executed immediately

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/ruff#6293]
in my codebase there's a `find` function where the lambda is executed immediately which means it's safe to use the loop variable this way, so i have to suppress this rule on all of its usages:
```py
foo = [1, 2, 3]
for bar in foo:
    find([1, 2, 3], lambda value: value == bar)  # noqa: B023
```
it would be nice if there was an option to specify functions where the lambda is executed immediately, like with `extend-immutable-calls`:
```toml
[tool.ruff.flake8-bugbear]
lambdas-executed-immediately = ["find"] # perhaps also a way of specifying which argument takes the lambda
```
