### ISSUE TITLE
Ruff should detect unreachable code but reports 'Missing explicit return', fixing it with `return None`

### ISSUE THREAD

**Issue by bittner** [astral-sh/ruff#6334]
In the code below Ruff should detect unreachable code, but it reports 'Missing explicit return'.

It tries to `--fix` the problem appending a `return None` line even after the unreachable code, which clearly makes no sense.

## Example

```python
# FILE: foo.py

def get_rates(data, dataframe_foo):
    """A data science example with data frames."""
    dt_tmp = data.copy()
    rates = (
        dt_tmp.sort_values(dataframe_foo.date_col)
        .groupby([dataframe_foo.id_col, dataframe_foo.bar_col])
        .agg(list)
    )
    rates = rates.reset_index().rename(columns={0: "baz"})
    foobar_rates = rates[["dki_id", "bar", "baz"]]
    return foobar_rates
    rates = rates.reset_index()
```

After running `ruff foo.py --fix` you get:

```diff
    return foobar_rates
    rates = rates.reset_index()
+   return None
```

Interestingly, with `ruff foo.py --fix --isolated` nothing gets changed.

## Ruff details

```console
$ ruff --version
ruff 0.0.282
```

Configuration in `pyproject.toml`:

```toml
[tool.ruff]
extend-exclude = []
extend-select = ["B", "BLE", "C4", "C90", "COM", "DJ", "DTZ", "EM", "G", "I", "N", "PIE", "PL", "PT", "PTH", "R", "RUF", "S", "SIM", "T10", "TID", "W", "YTT"]
extend-ignore = []

[tool.ruff.per-file-ignores]
"tests/**/*.py" = ["S101"]
```

## Maybe related

I found PR #5384, which seems to address the very issue. Interestingly, the configuration rule `RUF014` that the PR supposedly implements is not mentioned in any of the [recent releases](https://github.com/astral-sh/ruff/releases). (I tried to install Ruff from source code to verify the claim of the merged feature not being included, but my system ships a too-old version of `rustc`, which makes the build fail.)
