### ISSUE TITLE
[Autofix error] Failed to format

### ISSUE THREAD

**Issue by gaborbernat** [astral-sh/ruff#6412]
```python
from __future__ import annotations

from json import JSONDecodeError


def _as():
    try:
        pass
    except (JSONDecodeError, JSONDecodeError, TypeError):
        raise ValueError("")

```

```bash
❯ ruff check --fix magic.py

error: Autofix introduced a syntax error. Reverting all changes.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BAutofix%20error%5D

...quoting the contents of `magic.py`, the rule codes B014, EM101, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

magic.py:1:1: D100 Missing docstring in public module
magic.py:6:5: ANN202 Missing return type annotation for private function `_as`
magic.py:9:12: B014 Exception handler with duplicate exception: `JSONDecodeError`
magic.py:10:9: B904 Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
magic.py:10:9: TRY200 Use `raise from` to specify exception cause
magic.py:10:26: EM101 Exception must not use a string literal, assign to variable first
Found 6 errors.
```

```bash
❯ ruff --version
ruff 0.0.282
```

```toml
[tool.ruff]
select = ["ALL"]
line-length = 120
target-version = "py311"
isort = {known-first-party = ["events_gateway", "tests"], required-imports = ["from __future__ import annotations"]}
ignore = [
    "ANN101", # Missing type annotation for `self` in method
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "D203",  # `one-blank-line-before-class` (D203) and `no-blank-line-before-class` (D211) are incompatible
    "D212",  # `multi-line-summary-first-line` (D212) and `multi-line-summary-second-line` (D213) are incompatible
    "ANN102", #  Missing type annotation for `cls` in classmethod
]
```
