### ISSUE TITLE
Is there a way to raise `PT011` for any exception types?

### ISSUE THREAD

**Issue by harupy** [astral-sh/ruff#6473]
### Discussed in https://github.com/astral-sh/ruff/discussions/6382

<div type='discussions-op-text'>

<sup>Originally posted by **harupy** August  7, 2023</sup>
I want to disallow calling `pytest.raises` without `match` **regardless of the error type**. Is there a way to achieve that? We could use [raises-require-match-for](https://beta.ruff.rs/docs/settings/#flake8-pytest-style-raises-require-match-for) and specify all error types in a codebase there:

```toml
[tool.ruff.flake8-pytest-style]
raises-require-match-for = ["ALL", "ERROR", "TYPES", "IN", "THIS", "REPO", "..."]
```
</div>

Is there an easier way?
