### ISSUE TITLE
INP001 false positive in tests folder

### ISSUE THREAD

**Issue by flying-sheep** [astral-sh/ruff#6474]
The recommended Python + Pytest layout is

- `src/`
  - `mypkg/`
    - `__init__.py`
    - `subpkg/`
      - `__init__.py`
- `tests/`
  - `test_thing.py`
  - `test_more/`
    - `test_other_thing.py`

Notably, `tests` and all files under it *aren’t packages*. The [recommended import mode](https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html#tests-outside-application-code) enforces that you can’t import from them.

Therefore `INP001` shouldn’t trigger when `tests` is on top level of the project.

In fact, it would be great to have both a rule that enforces the opposite and to ensure that `tests/**/test_*.py` files don’t import things from each other.

**Comment by tjkuson** [comment]
I think this could be related to #6114.

**Comment by flying-sheep** [comment]
Pytest collects and imports individual files. That’s independent from Python’s namespace packages.

It’s possible that that other issue incidentally fixes this, but this is an independent issue.

**Comment by charliermarsh** [comment]
Interesting. To what degree is this specific to pytest? On the surface it feels like per-file-ignores is the right solution here…

**Comment by flying-sheep** [comment]
It’s very specific to Pytest. I’m coming from the perspective that when people have e.g.

```toml
[tool.ruff]
select = ['INP', 'PT']
```

```
project_dir
+- src/...
+- tests/
   +- test_foo.py
   +- test_bar/
      +- __init__.py
      +- test_bar_basic.py
```

then they should optimally see something like this:

```
tests/test_bar/__init__.py:1:1: PT030 File `tests/test_bar/__init__.py` found. Pytest test directories shouldn’t contain packages.
```

Currently they will see an instruction to do the opposite of the recommended route:

```
tests/test_foo.py:1:1: INP001 File `tests/test_foo.py` is part of an implicit namespace package. Add an `__init__.py`.
```

**Comment by sanmai-NL** [comment]
See also #8690

**Comment by Artalus** [comment]
For what it's worth, it seems that even _with_ the `__init__.py` file present, `ruff` still complains about the `INP001` (unlike the original flake linter):
```
[artalus@idpad foo]$ tree --gitignore
.
├── pyproject.toml
├── README.md
├── src
│   └── foo
│       └── __init__.py
├── tests
│   └── test_foo.py
└── uv.lock

[artalus@idpad foo]$ uv pip install flake8-no-pep420 ruff
Using Python 3.13.2 environment at: /tmp/420/.venv
Resolved 6 packages in 519ms
Installed 3 packages in 52ms
 + flake8==7.2.0
 + flake8-no-pep420==2.8.0
 + ruff==0.11.10

[artalus@idpad foo]$ flake8
./tests/test_foo.py:1:1: INP001 File is part of an implicit namespace package. Add an __init__.py?

[artalus@idpad foo]$ ruff check
tests/test_foo.py:1:1: INP001 File `tests/test_foo.py` is part of an implicit namespace package. Add an `__init__.py`.
Found 1 error.

[artalus@idpad foo]$ touch tests/__init__.py

[artalus@idpad foo]$ flake8

[artalus@idpad foo]$ ruff check
tests/test_foo.py:1:1: INP001 File `tests/test_foo.py` is part of an implicit namespace package. Add an `__init__.py`.
Found 1 error.
```

We ended up disabling `INP001` for the tests dir:
```toml
# /pyproject.toml
[tool.ruff.lint.per-file-ignores]
"tests/*" = [  # /* ensures it works for all subdirectories
    "INP001",  # "implicit namespace package" is invalid for pytest
]

# OR,

# /tests/ruff.toml
# inherit all settings from the main file
extend = "../pyproject.toml"
[lint]
ignore = [
    "INP001",
]
```
