### ISSUE TITLE
TCH001 TCH002 false negative – add msgspec.Struct support

### ISSUE THREAD

**Issue by Olegt0rr** [astral-sh/ruff#6571]
> TCH001 [*] Move application import `.objects.Issue` into a type-checking block

and 

> TCH002 [*] Move third-party import `myapp.types.Issue` into a type-checking block

```python
from __future__ import annotations

from msgspec import Struct

from myapp.types import Issue


class FullIssue(Struct):
    parent: Issue | None = None

```

Ruff v0.0.284 
target-version = "py39"

**Comment by charliermarsh** [comment]
Does it work as expected if you set [`runtime-evaluated-base-classes`](https://beta.ruff.rs/docs/settings/#flake8-type-checking-runtime-evaluated-base-classes)?

```toml
[tool.ruff.flake8-type-checking]
runtime-evaluated-base-classes = ["msgspec.Struct"]
```
