### ISSUE TITLE
Add sphinx documentation style to pydocstyle config

### ISSUE THREAD

**Issue by Eutropios** [astral-sh/ruff#6606]
Addition of sphinx documentation style to pydocstyle config as so:
```toml
[tool.ruff.pydocstyle]
        convention = "sphinx"
```
Currently pep257, google, and numpy documentation styles are supported. It'd be nice to have this major documentation style added as well.
