### ISSUE TITLE
UP007: Flags code even when python version is less than 3.10

### ISSUE THREAD

**Issue by bgianfo** [astral-sh/ruff#6740]
The documentation for `UP007` points to [PEP 604](https://peps.python.org/pep-0604/), which claims it targets python 3.10.

The ruff rule seems to currently run even if you are targeting python 3.9, is this a bug? I can't seem to determine if the PEP 604 syntax was backported to py39 or not? 

Current Ruff Version: 0.0.285 

```toml
[tool.ruff]
# Support Python 3.9+.
target-version = "py39"
````
