### ISSUE TITLE
PYI010: replace func stub's docstrings with '...' even if there already is one.

### ISSUE THREAD

**Issue by Prometheos2** [astral-sh/ruff#7021]
Hello,

I've noticed PYI010's autofix replaces function stubs' docstrings with ellipsis regardless of if there is one already or not.

### Minimal code snippet

```python
def function():
    """doc"""
    ...
```
### Details
* **The commands I invoked:** 
  * the VSC extension's autofix
  * `ruff . --fix`
  * `ruff . --fix --isolated --select "PYI"` (got a `error: Failed to converge after 100 iterations.` with this one; ~~will create a new issue soon~~)

* **The current Ruff version:** 0.0.286

### The current Ruff settings
* A _ruff.toml_ file on the project root (linted file is in a _typings_ subfolder)
```toml
select = [
	# ...
	"PYI",  # flake8-pyi
	# ...
]
include = ["*.py", "*.pyi", "*.ipynb", "pyproject.toml", "rust.toml"]
ignore = ["E501", "N999"]
target-version = "py38"
src = ["Phonebook_analyzer"]
```
 * Added a `# "PYI010"` in unfixable after the first command; no sure if it's relevant.   

Thanks for the linter, btw; it's really awesome!
