### ISSUE TITLE
Formatter causes E501 for long variable and attributes

### ISSUE THREAD

**Issue by aaravind100** [astral-sh/ruff#7407]
I'm testing the format option. Found that formatting scripts with long variables and attributes which are indented cases E501.

ruff check, would raise `11:89: E501 Line too long (92 > 88 characters)` for this snippet.

- formatted with black
```py
class Foo:
    some_very_long_attribute_name: str = ""

    def __getitem__(self, val):
        ...


def main() -> None:
    if True:
        some_very_long_variable_name_abcdefghijk = Foo()
        some_very_long_variable_name_abcdefghijk = (
            some_very_long_variable_name_abcdefghijk[
                some_very_long_variable_name_abcdefghijk.some_very_long_attribute_name
                == "This is a very long string abcdefghijk"
            ]
        )


if __name__ == "__main__":
    main()
```
- formatted with ruff
```py
class Foo:
    some_very_long_attribute_name: str = ""

    def __getitem__(self, val):
        ...


def main() -> None:
    if True:
        some_very_long_variable_name_abcdefghijk = Foo()
        some_very_long_variable_name_abcdefghijk = some_very_long_variable_name_abcdefghijk[
            some_very_long_variable_name_abcdefghijk.some_very_long_attribute_name
            == "This is a very long string abcdefghijk"
        ]


if __name__ == "__main__":
    main()
```

- pyproject.toml
```toml
[tool.ruff]
target-version = "py39"
line-length = 88
select = ["B", "C", "E", "F", "I", "W"]
ignore = ["E731"]

[tool.black]
line-length = 88
target-version = ["py39"]
```

- version
`Python 3.9.5`
`ruff 0.0.289`
`OS Ubuntu 22.04.3 LTS(WSL)`

- Additional info
In the original script the class Foo is a pandas dataframe and this pattern is quite common.
