### ISSUE TITLE
Excluding a folder containing braces in its name fails

### ISSUE THREAD

**Issue by LKajan** [astral-sh/ruff#7959]
If folder containing braces in its name is configured to the `extend-exclude` ruff fails to run. `ruff .` produces an error:
```
ruff failed
  Cause: error parsing glob 'C:\Users\<>\cookiecutter-plugin\{{cookiecutter.plugin_package}}': nested alternate groups are not allowed
```

Ruff version: 0.0.292

**My project structure and configuration:**
```
./
├ {{cookiecutter.project_directory}}
├ hooks/
| ├ post_gen_project.py
├ pyproject.toml
```

```toml
# pyproject.toml
[tool.ruff]
extend-exclude = ["{{cookiecutter.plugin_package}}"]
```

**Comment by charliermarsh** [comment]
These are globs, so you need to do some escaping:

```toml
[tool.ruff]
extend-exclude = [
  '\{\{cookiecutter.plugin_package\}\}'
]
```

TOML requires single quotes there, I think, but I tested this myself. Let me know if it works for you!
