### ISSUE TITLE
Add option to mark test file paths for `flake8-pytest-style`

### ISSUE THREAD

**Issue by a-recknagel** [astral-sh/ruff#8145]
I don't want to run any linters for my test code, except for `flake8-pytest-style`. It would be nice if I could give it the path(s) to the test files somehow, so that I don't need to have two distinct configurations for running `ruff`.

workaround:
```shell
$ ruff src  # uses my config, checks my source code
$ ruff --isolated --select PT tests  # only uses PT, checks my test code
```

And the second line would also need to include any other `flake8-pytest-style` or top-level options that it needs. Being able to set something like 

```toml
[tool.ruff.flake8-pytest-style]
test-linting-only-path = ["tests"]
```
which would exclude these files/folders from any other linters given a call `ruff src tests` would help.

**Comment by dhruvmanila** [comment]
Do you think using [`extend`](https://docs.astral.sh/ruff/settings/#extend) would help in your scenario? So, you would add a `pyproject.toml` in the `tests/` directory which would `extend` from the root `pyproject.toml` file and add a [`extend-select = ["PT"]`](https://docs.astral.sh/ruff/settings/#extend-select) to it.

**Comment by ThiefMaster** [comment]
For me that would not help as I do not have a `tests/` directory. Instead, I have test files next to the files to be tested. e.g. `mypkg/util/string.py` has its test in `mypkg/util/string_test.py` and so on.

I think ideally it would apply the [pytest rules for test discovery](https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html#conventions-for-python-test-discovery), ideally with override settings or parsing of the [repective pytest.ini options](https://docs.pytest.org/en/7.1.x/example/pythoncollection.html#changing-naming-conventions).

**Comment by charliermarsh** [comment]
I think mirroring the pytest rules for discovery would be sensible. It would also solve https://github.com/astral-sh/ruff/issues/8703, and arguably solve https://github.com/astral-sh/ruff/issues/6474.

**Comment by charliermarsh** [comment]
However, I definitely want to avoid parsing `pytest.ini` and interpreting pytest configuration -- it's just a huge pain to implement and maintain (and also requires that we know the pytest version and keep our settings in-sync with pytest's settings). So if we _did_ do this, we'd need to stick to the defaults, _or_ add our own limited configuration.

**Comment by dhruvmanila** [comment]
Thanks! I think we can close this one out as the suggested solution should work for @a-recknagel case but happy to re-open if it doesn't.

As for the @ThiefMaster case, I'll open a new issue to track the change (#8794).

**Comment by a-recknagel** [comment]
No need to re-open, `extend` works for me. Thanks!

**Comment by a-recknagel** [comment]
just to spell it out once in case someone has the same issue, this is what I ended up doing which I'm happy with:

**project structure**
```
.
├── src
│   └── my_package
│       ├── __init__.py
│       └── foo.py
├── tests
│   ├── ruff.toml
│   └── my_package
│       └── test_foo.py
└── pyproject.toml
```

**pyproject.toml**
```toml
["..."]  # other settings that don't matter here
[tool.ruff]
# settings I want to share between both src and test linting
src = ["src"]
isort = { combine-as-imports = true, force-wrap-aliases = true }
# src-specific rule set
select = ["E", "F", "W", "N", "I", "UP", "..." , "D", "RUF"]
```

**tests/ruff.toml**
```toml
# the magic word I was missing
extend = "../pyproject.toml"
# test-specific rule set
select = ["F", "N", "I", "PT", "RUF"]
```

**what I run**
```shell
$ ruff src
$ ruff tests --config tests/ruff.toml
```
