### ISSUE TITLE
Docs: README.md `tool.ruff.lint` fault

### ISSUE THREAD

**Issue by thernstig** [astral-sh/ruff#8217]
```toml
[tool.ruff.lint]
# 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
select = ["E", "F", "B"]
```

The comment says it only enables flake8-bugbear in addition to defaults, but the default is this according to the same page:

```toml
[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F"]
ignore = []
```

So the above is enabling all `E` rules in addition to the flake8-bugbear rules.

**Solution**

Change to:

```toml
[tool.ruff.lint]
# 1. Enable flake8-bugbear (`B`) rules and all (`E`) rules, in addition to the defaults.
select = ["E", "F", "B"]
```
