### ISSUE TITLE
`format|lint.exclude` does not exclude directories

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#8267]
Given:

```toml
[tool.ruff.lint]
exclude = ["directory"]
```

with `foo.py` in `directory`

```python
import os
```

```bash
cargo run -p ruff_cli -- check .
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `/Users/crmarsh/workspace/ruff/target/debug/ruff check .`
warning: Detected debug build without --no-cache.
directory/foo.py:1:8: F401 [*] `os` imported but unused
Found 1 error.
```

The file is excluded when changing the configuration to 

```toml
[tool.ruff.lint]
exclude = ["directory"]
```
