### ISSUE TITLE
Invalid flake8-quotes rule

### ISSUE THREAD

**Issue by wu-clan** [astral-sh/ruff#8269]
This is pyproject.toml for ruff:
```toml
[tool.ruff]
line-length = 120
cache-dir = "./.ruff_cache"

[tool.ruff.isort]
order-by-type = true

[tool.ruff.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"
```

When I change `[tool.ruff.flake8-quotes]` to `[tool.ruff.lint.flake8-quotes]`, `ruff check .` still doesn't work!

When I use `[tool.ruff.format]`, `ruff format .` starts to work

```toml
[tool.ruff.format]
quote-style = "single"
```

```
> pdm run ruff --version
ruff 0.1.2
```

**Comment by dhruvmanila** [comment]
Hey, thanks for opening this issue. Is it that the `ruff check` command isn't taking the `flake8-quotes` settings when performing a fix? Or is it a compatibility issue between the linter and formatter? If possible, can you please provide a minimal code snippet to test against?

**Comment by wu-clan** [comment]
Because I check the root directory, I want the settings to be applied automatically

MRE:
```py
def mre_ruff_flake8_quotes():
    """
    Ruff flake8 quotes check
    """
    foo = "bar"

    foo2 = """
    bar
    """

    print(foo, foo2)
```

**Comment by wu-clan** [comment]
Because I check the root directory, I want the settings to be applied automatically

MRE:
```py
def mre_ruff_flake8_quotes():
    """
    Ruff flake8 quotes check
    """
    foo = "bar"

    foo2 = """
    bar
    """

    print(foo, foo2)
```
Then set up the rules in my description above

**Comment by MichaReiser** [comment]
There are two ways how you can enforce consistent quotes:

* Formatter: Using `ruff format`. This seems to work for you, if I understood you correctly
* Linter: Using `Q001-Q003`. 

What's best for you depends on your desired setup. We recommend to either use the Formatter or the `flake8-quote`  rules, but not both together (the formatter makes the lint rules redundant). 

To use the `flake8-quote` rules. I think what's missing is that you enable them using 

```toml
[tool.ruff.lint]
extend-select = ["Q"]
```

You probably want to add `"I"` if you intend to use `isort`.
