### ISSUE TITLE
`fmt: skip` does not work on internal structures

### ISSUE THREAD

**Issue by SigureMo** [astral-sh/ruff#8319]
This is a minimal reproduction:

```toml
# pyproject.toml
[tool.ruff]
line-length = 120

[tool.black]
line-length = 120
```

```python
# ruff-fmt-skip-repro.py
x = [
    {
        1: 2
    }  # fmt: skip
]
```

black left unchanged:

```bash
❯ black --version           
black, 23.10.1 (compiled: no)
Python (CPython) 3.12.0

❯ black ruff-fmt-skip-repro.py
All done! ✨ 🍰 ✨
1 file left unchanged.
```

But ruff will format the code:

```bash
❯ ruff --version                    
ruff 0.1.3

❯ ruff format ruff-fmt-skip-repro.py           
1 file reformatted
```

The formatted code shown below:

```python
x = [
    {1: 2}  # fmt: skip
]
```
