### ISSUE TITLE
Ruff formatter missing character limit argument

### ISSUE THREAD

**Issue by ryan-cpi** [astral-sh/ruff#8352]
We are using the ruff pre-commits formatter however there doesn't seem to be a way to pass in an argument to set the line character limit without having a config file dedicated for this. Is it possible to add an argument for this `-l 120`?

```yaml
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.2
    hooks:
      - id: ruff-format
```
