### ISSUE TITLE
Ruff not working with fixing imports force-single-line=true

### ISSUE THREAD

**Issue by SanketDG** [astral-sh/ruff#8456]
`test.py`
```python
from tests.helpers.db import (
    setup_db,
    setup_db2,
)

setup_db()
setup_db2()
```

`pyproject.toml`
```toml
[tool.ruff]
line-length = 120
exclude = ["entrypoint.py"]

[tool.ruff.isort]
force-single-line = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
```

`ruff check` or `ruff format` does not output anything.
Also tried ` ruff check test.py --isolated --fix`

```
ruff --version                                  
ruff 0.1.3
```
