### ISSUE TITLE
ruff format double and single quotes

### ISSUE THREAD

**Issue by Xiwang-Li-Walmart** [astral-sh/ruff#8527]
Can we have an option to select either double or single quote for ruff formatting? 
and even just ignore  this double or single quote formatting by add `-S` like in Black?

Thank you.

**Comment by charliermarsh** [comment]
I believe this exists as [`quote-style`](https://docs.astral.sh/ruff/settings/#format-quote-style), e.g., in your `pyproject.toml`:

```toml
[tool.ruff.format]
quote-style = "single"
```
