### ISSUE TITLE
[D417] Missing argument descriptions in the docstring for `**kwargs` and `*args` should be allowed

### ISSUE THREAD

**Issue by mikeweltevrede** [astral-sh/ruff#8605]
I would expect D417 to not require `*args` and `**kwargs` to be put in the descriptions. Maybe this is not good practice, in which case please let me know.

* A minimal code snippet that reproduces the bug.
```
def f(*args, **kwargs):
    """Description"""
```

* The command you invoked (e.g., `ruff /path/to/file.py --fix`), ideally including the `--isolated` flag.
`pre-commit install` with the following config:

```
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: name-tests-test
        exclude: ^tests/utils/
      - id: no-commit-to-branch
      - id: trailing-whitespace

```

* The current Ruff settings (any relevant sections from your `pyproject.toml`).

```
[tool.poetry.group.dev.dependencies]
pre-commit = "3.5.0"
ruff = "0.1.4"
pre-commit-hooks = "4.5.0"

[tool.ruff.lint]
extend-select = [
    "D",  # pydocstyle
]
ignore = ["B026", "D100", "D415", "ANN101", "ANN102", "ANN002", "ANN003"]

[tool.ruff.lint.pydocstyle]
convention = "google"
```

* The current Ruff version (`ruff --version`).
    * 0.1.4
