### ISSUE TITLE
Q000 fixer does not remove obsolete backslash-escape inside string after changing quotes

### ISSUE THREAD

**Issue by ThiefMaster** [astral-sh/ruff#8617]
ruff.toml:
```toml
select = ['Q']

[flake8-quotes]
inline-quotes = 'single'
multiline-quotes = 'single'
docstring-quotes = 'double'
avoid-escape = true
```

Code:
```python
a = "hello\"world"
```

ruff output:
```
[adrian@claptrap:/tmp/rufftest]> ~/dev/ruff/target/release/ruff check --no-cache test.py
test.py:1:5: Q000 [*] Double quotes found but single quotes preferred
Found 1 error.
[*] 1 fixable with the `--fix` option.
```

And after running with `--fix` added:

```python
a = 'hello\"world'
```

While not invalid, this is ugly - in particular since `avoid-escape` is enabled. It should have been this:

```python
a = 'hello"world'
```
