### ISSUE TITLE
Exclude applied to root, when used with pre-commit

### ISSUE THREAD

**Issue by ni-co-la** [astral-sh/ruff#9023]
Files are not checked with Ruff running in pre-commit, if the git repository is inside a build directory. 

### Steps to reproduce

The setup is very basic.
Create a directory `build`.
Initialize git inside this directory. 
Create a Python file, which is violating Ruff rules.
Install pre-commit hook (with the pre-commit Python package).
Run pre-commit on all files -> the Python file will not be checked.

### Project structure
```
build
    |- .git
    |- .pre-commit-config.yaml
    |- test.py
```

### Executed commands: 
``` shell
mkdir build
cd build
git init
# Add .pre-commit-config.yaml and test.py to git
python -m pre_commit install
python -m pre_commit run --all-files --verbose # will not check test.py
python -m ruff check . # detects unused import
```
 
### Files
test.py
``` python
#!/usr/bin/env python3

import ruff

def main():
    pass

if __name__ == '__main__':
    main()
```

.pre-commit-config.yaml 
``` yaml
repos:
-   repo: https://ch03git.phonak.com/PRSW/ruff-pre-commit.git
    rev: v0.1.6
    hooks:
    -   id: ruff
        types: [python]
```

### Versions
pre-commit==3.5.0
ruff==0.1.7
