### ISSUE TITLE
E712 fix results in unsafe behavior

### ISSUE THREAD

**Issue by DavidSlayback** [astral-sh/ruff#9063]
If Ruff is allowed to check for and fix E712 errors, this can result in unexpected behavior with things like pandas DataFrames. Example:
```python
mask = (df["bool_col"] == True) & (df["other_col"].isna())
# If we add noqa, we're ok
mask = (df["bool_col"] == True) & (df["other_col"].isna())  & (df["other_col"].isna()) # noqa: E712
# But if we let ruff fix as part of a pre-commit...
# ruff check . --fix
mask = (df["bool_col"] is True) & (df["other_col"].isna()) 
```
The original behavior produces a mask for each operand and combines them. The "fix" makes the first operand always return False, which means the whole mask is False.

**Ruff version**: v0.1.6

I think the desired behavior would be to either consider the fix unsafe or to favor removing `== True` and `!= True`, but the latter might be difficult (because the correct equivalent to != in Pandas is `~df`, not `!df` or `not df`

**Comment by zanieb** [comment]
Please see https://github.com/astral-sh/ruff/issues/4560

This fix should already be marked as unsafe and not applied unless you've opted into unsafe fixes e.g.

```
❯ ruff check example.py --isolated --no-cache --select E712 --fix
example.py:1:27: E712 Comparison to `True` should be `cond is True` or `if cond:`
Found 1 error.
No fixes available (1 hidden fix can be enabled with the `--unsafe-fixes` option).
❯ ruff check example.py --isolated --no-cache --select E712 --fix --unsafe-fixes
Found 1 error (1 fixed, 0 remaining).
```

**Comment by DavidSlayback** [comment]
Hmm...sorry about that, I'll have to figure out how the auto fix got triggered, our pre-commit doesn't specify `--unsafe-fixes`

**Comment by charliermarsh** [comment]
Hmm, could you have unsafe-fixes = true set in your pyproject.toml or ruff.toml file?

**Comment by DavidSlayback** [comment]
No `ruff.toml`, `pyproject.toml` doesn't specify anything about the fixes, and `.pre-commit-config.yaml` section is:
```yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.6
    hooks:
      - id: ruff
        name: "Lint and fix code using Ruff"
        args: [ --fix, --exit-non-zero-on-fix ]
        stages: [commit]
```
