### ISSUE TITLE
ruff VSCode extension erases entire file on save

### ISSUE THREAD

**Issue by bdewilde** [astral-sh/ruff#9123]
After updating/reloading a couple extensions in VSCode -- one of which may have been Ruff, I'm not 100% sure -- the Ruff extension suddenly started erasing entire Python files on save. I've disabled/re-enabled and uninstalled/re-installed, but that doesn't change the behavior. I've further narrowed it down to the "format imports" command -- "format document" does not erase the module -- but disabling the "organize imports" behavior in settings somehow does not stop saves from erasing the file. The corresponding configs in my VSCode settings and `pyproject.toml` tools have not changed.

I don't have a code snippet, but I do have a gif demonstrating the phenomenon:

![ruff-surprise](https://github.com/astral-sh/ruff/assets/2514535/ec86f690-6dc0-45e5-afbc-2cdddb690f5c)

This is quite unexpected, and I do not understand what's gone wrong. I have the latest version of both the `ruff` VSCode extension (v2023.52.0) and Python package (v0.1.8) installed. Here's the relevant config:

```json
  "[python]": {
    "editor.defaultFormatter": "charliermarsh.ruff",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.fixAll.ruff": "always",
      "source.organizeImports.ruff": "always"
    },
  }
```

and

```toml
[tool.ruff]
# ignore line-length violations, None comparisons
ignore = ["E501", "E711"]
line-length = 88
indent-width = 4
target-version = "py310"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "F401"] # imports not at top of cell and unused imports
```

Assuming this must be user error, but gosh I don't know what or how. Thanks in advance for your help.
