### ISSUE TITLE
[Linter panic] Fixing TCH003 fails when no `TYPE_CHECKING` block exists and `exempt-modules` is empty

### ISSUE THREAD

**Issue by picnixz** [astral-sh/ruff#9196]
I'm not sure that it's the place to ask since this bug appears to be caused by `[tool.ruff.lint.flake8-type-checking]`. Anyway, with the configuration

```toml
[tool.ruff]
target-version = 'py311'
ignore = ['all']
select = ['TCH']

[tool.ruff.lint.flake8-type-checking]
exempt-modules = []
``` 

invoking 

```bash
python3.11 -m ruff file.py --fix --unsafe-fixes
``` 

on

```python
from __future__ import annotations

from typing import Final
from collections.abc import Mapping

Const: Final[Mapping] = {}
```

fails with

```text
panicked at /home/runner/work/ruff/ruff/crates/ruff_text_size/src/range.rs:48:9:
assertion failed: start.raw <= end.raw
Backtrace:    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: __libc_start_main
             at /usr/src/debug/glibc-2.26-lp152.26.12.1.x86_64/csu/../csu/libc-start.c:308
  17: <unknown>
```

But the following succeeds:

```python
from __future__ import annotations

from typing import TYPE_CHECKING, Final
from collections.abc import Mapping

if TYPE_CHECKING:
    from collections.abc import Sequence

Const: Final[Mapping[str, Sequence]] = {}
```

and gets reformatted as

```python
from __future__ import annotations

from typing import TYPE_CHECKING, Final

if TYPE_CHECKING:
    from collections.abc import Mapping
    from collections.abc import Sequence

Const: Final[Mapping[str, Sequence]] = {}
```

I think it's because the `TYPE_CHECKING` block does not exist yet that it's like that. However, if the block is empty and only `typing` imports exist, it also fails:

```python
from __future__ import annotations

from typing import TYPE_CHECKING, Final

if TYPE_CHECKING:
    pass

Const: Final[float] = 1
```

Now, if I change

```toml
[tool.ruff.lint.flake8-type-checking]
exempt-modules = []
```

to 

```toml
[tool.ruff.lint.flake8-type-checking]
exempt-modules = ['typing']
```

it works as intended.

### Environment

```text
Platform:              linux; (Linux-5.3.18-lp152.106-default-x86_64-with-glibc2.26)
Python version:        3.11.6 (main, Nov 29 2023, 14:46:32) [GCC 7.5.0])
Python implementation: CPython
ruff version:          0.1.8
```
