### ISSUE TITLE
line-length for formatter doesn't follow the E501 lint rules.

### ISSUE THREAD

**Issue by jungwookim** [astral-sh/ruff#9289]
I want to set the proper line length but its behaviour is pretty weird. I've attached the reproducible example code and my configurations below.

```bash
$ ruff --version
ruff 0.1.8

$ ruff check a.py
a.py:5:81: E501 Line too long (108 > 80)
a.py:9:81: E501 Line too long (96 > 80)
```

After I fix the E501 above with new line, I format it with `ruff format a.py`. It produces line too long again.

In other words, ruff format doesn't do anything with wrap lines even they violate their own rule (i set line-length = 80 but it rolls back)

## pyproject.toml
I skipped some unrelated configurations.

```toml
[tool.ruff]
line-length = 80
indent-width = 4

# Assume Python 3.10
# NOTE: Need to be same as DEFAULT_PYTHON_TAG in build_tools/w4.bzl.
target-version = "py310"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "E501"]
ignore = []

[tool.ruff.lint.pycodestyle]
max-line-length = 80
```

## example code

```python
# a.py (origin)
def line_too_long_test_fn():
    config_enums = {'DataType': {'TEST_DATA_1': 0, 'TEST_DATA_2': 1}}
    test_data_1 = {
        'LessThan80': 'This is a test string that is less than 80 characters',
        'MoreThan80CharactersMoreThan80Characters': 'This is a test string that is more than 80 characters',
    }
    test_data = {
        config_enums.DataType.TEST_DATA_1: test_data_1.LessThan80,
        config_enums.DataType.TEST_DATA_2: test_data_1.MoreThan80CharactersMoreThan80Characters,
    }

    return test_data
```

```python
# a.py (I fixed)
def line_too_long_test_fn():
    config_enums = {'DataType': {'TEST_DATA_1': 0, 'TEST_DATA_2': 1}}
    test_data_1 = {
        'MoreThan80CharactersMoreThan80Characters':
            'This is a test string that is more than 80 characters',
    }
    test_data = {
        config_enums.DataType.TEST_DATA_2:
            test_data_1.MoreThan80CharactersMoreThan80Characters,
    }

    return test_data
```

```python
# a.py (after ruff format)
def line_too_long_test_fn():
    config_enums = {'DataType': {'TEST_DATA_1': 0, 'TEST_DATA_2': 1}}
    test_data_1 = {
        'MoreThan80CharactersMoreThan80Characters': 'This is a test string that is more than 80 characters',
    }
    test_data = {
        config_enums.DataType.TEST_DATA_2: test_data_1.MoreThan80CharactersMoreThan80Characters,
    }

    return test_data
```

I guess it happens on dictionary data or edge cases or a bug?..?
