### ISSUE TITLE
`per-file-ignores` with ALL creates a false positive

### ISSUE THREAD

**Issue by tooruu** [astral-sh/ruff#9297]
Given the following Python file
```py
# T201 disallows `print`
print("foo")  # noqa: T201
```
and the following Ruff configuration
```toml
select = ["ALL"]

[per-file-ignores]
"file.py" = ["ALL"]
```
`ruff check` will still raise error ``RUF100 [*] Unused `noqa` directive (unused: `T201`)``.
