### ISSUE TITLE
New rule: disallow code in `__init__` modules

### ISSUE THREAD

**Issue by samueljsb** [astral-sh/ruff#9848]
Could we add the rules from [flake8-empty-init-modules/](https://pypi.org/project/flake8-empty-init-modules/) (`EIM001`/`EIM002`) to `ruff`?

These disallow code in `__init__` modules (EIM001) or disallow anything other than imports and assignment to `__all__` (EIM002).

Disclaimer: I am the author of the flake8 plugin. I'd be interested in trying to implement the checks for `ruff` if they would be welcome.

**Comment by andersfylling** [comment]
This would be really helpful to avoid surprising cyclic dependency errors.

**Comment by andersfylling** [comment]
for people that want something temporary using pre-commit:

> empty-init-hook.py
```py
import sys
import os

non_empty_files = False

files = sys.argv[1:]
for file in files:
    if os.path.getsize(file) > 0:
        non_empty_files = True
        print(f"not empty: {file}")

if non_empty_files:
    exit(1)
```

> .pre-commit.yaml
```
default_language_version:
  python: python3.12
repos:
- repo: local
  hooks:
  - id: empty-init-files
    name: empty init files
    entry: uv run python ./empty-init-hook.py
    language: system
    files: __init__.py$
    pass_filenames: true
```

Running this would take <1s for repos with hundreds of python files, and the output for failed cases looks like:
```
> uv run pre-commit run --all-files

empty init files.........................................................Failed
- hook id: empty-init-files
- duration: 0.59s
- exit code: 1

not empty: my_app/__init__.py
