### ISSUE TITLE
Docs request: linking `mypy`'s `ignore-without-code` in `PGH003`

### ISSUE THREAD

**Issue by jamesbraza** [astral-sh/ruff#9863]
`mypy` has an opt-in rule [`ignore-without-code`](https://mypy.readthedocs.io/en/stable/error_code_list2.html#check-that-type-ignore-include-an-error-code-ignore-without-code) that prevents blanket type ignores.

```toml
[tool.mypy]
enable_error_code = ["ignore-without-code"]
```

It would be cool to link this in the PGH003 docs: https://docs.astral.sh/ruff/rules/blanket-type-ignore/#blanket-type-ignore-pgh003

As it is an alternate configuration route to eliminate the need for `PGH003`
