### ISSUE TITLE
Different length sort behavior against isort

### ISSUE THREAD

**Issue by yanyongyu** [astral-sh/ruff#9870]
I'm trying to migrate isort and black to ruff but encountered some problems when using ruff's isort configs.

Ruff version 0.2.1.

Suppose I have a first-party package named `package` and the test code is:

```python
from package.utils import a
from package.func import function
```

with the ruff config:

```toml
[tool.ruff.lint]
select = ["I"]

[tool.ruff.lint.isort]
length-sort = true
force-sort-within-sections = true
```

ruff will report import order error and fix it into:

```python
from package.func import function
from package.utils import a
```

but isort sorts it as the origin test code given above.

I make one more test, renaming the `package.func` to `package.function`:

```python
from package.utils import a
from package.function import function
```

this time ruff does not report any error. It seems ruff sort the import order by module name length instead of import expression length?

**Comment by charliermarsh** [comment]
Can you clarify for me -- if I run `isort` over:

```python
from package.utils import a
from package.func import function
```

With `length_sort = true`, it rewrites to:

```python
from package.func import function
from package.utils import a
```

In my testing, Ruff has the same behavior. But it seems like you're seeing different behavior with isort?

**Comment by yanyongyu** [comment]
i sort the code with:

```bash
isort --profile black --length-sort --force-sort-within-sections package/__init__.py
```

**Comment by yanyongyu** [comment]
Or use the pyproject.toml to config isort:

```toml
[tool.ruff.lint]
select = ["I"]

[tool.ruff.lint.isort]
length-sort = true
force-sort-within-sections = true

[tool.isort]
profile = "black"
length_sort = true
force_sort_within_sections = true
```

then sort the imports with `isort .`

the output code is:

```python
from package.utils import a
from package.func import function
```
