### ISSUE TITLE
How could I disable autoremove unused import?

### ISSUE THREAD

**Issue by ErnestDong** [astral-sh/ruff#9873]
I usually write python code in vscode as follows:
```python
#%%
import requests
import pandas as pd

res=requests.get(...)
```

where `#%%` creates a new notebook cell to run, `pandas` will be used to parse request JSON.

But Ruff will auto-remove unused imports and delete the `pandas` import. It is a burden to my mind that I need to use the temporary unused `pandas` before saving the file. How to fix that?

**Comment by charliermarsh** [comment]
You can mark the rule as unfixable in your Ruff configuration. For example, create a `ruff.toml` with...

```toml
[lint]
# Disable fix for unused imports (`F401`).
unfixable = ["F401"]
```
