### ISSUE TITLE
[Feature Request] Exclude option in per-linter configuration

### ISSUE THREAD

**Issue by AAraKKe** [astral-sh/ruff#9930]
## Description
Hi team! I started with Ruff a couple of days ago for a side project, and I love it. Not only because of how fast it is but also because it removes the need to maintain several configuration files since now everything can live in the `pyproject.toml` file of the project (I am looking to you, flake8...).

I have been looking into the configuration and have not found the option I am asking for here, if it is there, forgive me for the issue. Just point in the right direction, and thanks a lot! 

I am having an issue with isort and the lack of `exclude` option at a per-linter level. We have an `exclude` top-level option to tell Ruff to exclude given files from everything. Then we have a dedicated lint `exclude` option so we can decide what files not to lint. However, given that Ruff provides so many _linters_ when linting, it would be nice if we could also have exclude for each one of them. When running each feature, each one would run on any file that is not excluded by a combination of any `exclude` up to its node.

I am saying this because, while isort is great, imports sometimes can be sensitive to sorting. I know that is not ideal, and modules should be importable in a stand-alone manner, but there are use cases where importing things in a `__init__` in a certain way is done on purpose for specific reasons. I wouldn't like to exclude `__init__` files from linting completely, but I would love to be able to not run isort in them.

## Example use case
As an example, I am building an app in which there are hundreds of handlers. These handlers then need to be registered on the app, and we have built it in such a way that just defining the handler in the package and decorating it with a `Registry.register` method registers them. This removes the need to keep registering handlers. However, in order for this to happen automagically, the init needs to be written with imports in such a way that when the handler is imported, the decorator already exists to avoid circular dependencies.

This is known and documented in the project and everyone is onboard with the solution as it saves a huge amount of boilerplate, but we need to disable linting in `__init__` files to avoid isort breaking this feature.

Thanks a lot!

**Comment by charliermarsh** [comment]
This is sort of the intent of [`per-file-ignores`](https://docs.astral.sh/ruff/settings/#lint_per-file-ignores) -- have you tried that? E.g.:

```toml
[tool.ruff.lint.per-file-ignores]
# Disable the isort rules in `__init__.py` files.
"__init__.py" = ["I"]
```

**Comment by AAraKKe** [comment]
Actually I tried it but I thought it was not working as expected. But it does! I was validated whether the VSCode extension reports something to validate the configuration and for some reason the extension misses this configuration. Is it because there are options the extension does not recognize?

The block of imports appears underlined as if it needed to be formated but if I run Ruff it is not sorted, as expected.

**Comment by MichaReiser** [comment]
I'm glad to hear that `per-file-ignores` works for you. 

The VS Code extension supports all configuration settings.  Can you share a screenshot of what you're seeing? Do you have the `isort` plugin (not ruff, the standalone isort plugin) installed and it conflicts with ruff's settings?

**Comment by AAraKKe** [comment]
Sure, this is what I see in VSCode on the `__init__.py` file.

![imagen](https://github.com/astral-sh/ruff/assets/2953658/fed0a3d1-837e-4e54-8b44-0476482daa14)

As you can see, it is Ruff, the one that is complaining about the sorting.

The configuration in my `pyproject.toml` file is the following.

```toml
[tool.ruff]
line-length = 120
indent-width = 4
exclude = [".hatch", ".git", ".pytest_cache", ".mypy_cache", ".ruff_cache", "dist"]
src = ["mitup_bot", "tests"]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = ["SIM117"]

[tool.ruff.lint.isort]
known-first-party = ["mitup_bot", "tests"]
# Eensure alembic is not confused with our local alembic folder
known-third-party = ["alembic"]

[tool.ruff.lint.pycodestyle]
max-doc-length = 120
max-line-length = 120

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
```

I do have the sort extension installed, but it is disabled for this workspace since Ruff is handling it.

The warning in those lines goes away if I add the `# isort: skip_file` line at the top. That is why I thought the extension might not recognize all the options from `pyproject.toml`. If I run `ruff`, it does not complain about those imports in the `__init__.py` file.

Thanks!
